### ISSUE TITLE
Making a payment in CMS using logged in user as customer wipes out address information from order.

### ISSUE THREAD

**Issue by mambose** [craftcms/commerce#2522] opened 2021-08-24 04:48 UTC
### Description
When I create an order in the CMS using myself as the customer when I make a payment on the order my billing information is cleared out. 

### Steps to reproduce

1. Remove all addresses saved under your customer profile first.
2. Create an order with yourself as the customer
3. Add a new billing address
4. Add line items
5. Click `Update Order`
6. Make a payment
7. View your order and billing information will be missing

Also, addresses entered during the ordering process are not saved to your customer profile is this intentional? 

### Additional info

- Craft CMS version: 3.7.8
- Craft Commerce version: 3.4.2
- PHP version: 8.0.8
- Database driver & version: MySQL 5.7.35
- Plugins & versions:

**Comment by pdaleramirez** [comment] 2021-08-31 08:07
@mambose I've tested this but can't reproduce the issue where the address values are missing in the address section. Associating the address to a customer after order is created isn't functional yet but that would be a good enhancement to have.

**Comment by boboldehampsink** [comment] 2021-12-07 18:04
I'm also seeing that addresses are disappearing, maybe has something to do with https://github.com/craftcms/commerce/issues/2555?

**Comment by pdaleramirez** [comment] 2021-12-14 08:18
@boboldehampsink The issue on #2555 has been fixed since version `3.4.4`

**Comment by nfourtythree** [comment] 2021-12-14 08:26
Hi @mambose 

Further to @pdaleramirez 's comment saying the issue was fixed in `3.4.4` we have also got a feature request for copying addresses from an order to a customer, you can find that here: #2282

If updating does not fix your problem could you check if you are defining any custom address validation rules? This was the issue we discovered with @boboldehampsink 's project in that when using `EVENT_DEFINE_RULES` on the `Address` module the `$rules` were being completely overwritten rather than appended to. Due to the way that mass assignment of data to a model in Yii this changed how addresses were being copied when an order completed.

I believe one of these two things will fix your issue so will close this for now. If you can still replicate the issue after checking those things please leave a comment and we can reopen the issue and look into it further.

Thanks!

**Closed by nfourtythree** 2021-12-14 08:26 UTC
Labels: 💡 enhancement, 📝 order edit, 🏠 addresses
