### ISSUE TITLE
[5.x]: EVENT_AFTER_COMPLETE_ORDER triggered before payment completion

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/commerce#3666] opened 2024-09-10 12:27 UTC
### What happened?

**Description:**  
The `EVENT_AFTER_COMPLETE_ORDER` event, as described in the [documentation](https://craftcms.com/docs/commerce/5.x/extend/events.html#aftercompleteorder), should be triggered after an order is marked as complete, typically after successful payment. However, this event is triggered prematurely when rendering the payment form using:

```twig
{{ cart.gateway.getPaymentFormHtml() }}
```

This causes the event to fire before the payment is completed, leading to unexpected behavior. We would expect the event to only trigger once the payment has been fully processed and confirmed.

### Steps to reproduce:

1. Create an order and add items to the cart.
2. Add a payment form in your template using `{{ cart.gateway.getPaymentFormHtml }}`.
3. Observe that the `EVENT_AFTER_COMPLETE_ORDER` is triggered before the payment process is finished, specifically when using the Stripe gateway.

### Expected behavior:

The `EVENT_AFTER_COMPLETE_ORDER` event should trigger only after the payment has been successfully processed and the order is marked as complete.

### Actual behavior:

The `EVENT_AFTER_COMPLETE_ORDER` event is triggered when the payment form is rendered, even though the payment has not yet been completed.

### Craft CMS version

5.4.2

### Craft Commerce version

5.1.0.1

### Installed plugins and versions

-

**Comment by lukeholder** [comment] 2024-09-13 02:57
@romainpoirier We are unable to reproduce this. The event is not raised when rendering the payment form.

The only thing I can think of is you might be rendering the form for a zero value order/cart and have `freeOrderPaymentStrategy` store config setting set to "Free orders complete immediately"?

If that isn’t it, could you possibly send through your composer.json, composer.lock, DB dump, as well as payment templates to support@craftcms.com and reference this issue.

Thanks!

**Comment by romainpoirier** [comment] 2024-09-16 09:57
Yes, that's correct, the `freeOrderPaymentStrategy` setting ("_Free orders complete immediately_") is enabled.

It seems that this issue occurs when the cart contains only one item with a price set to €0.00. Is it expected behavior that such an error is triggered without displaying the reason for the payment form not showing? Alternatively, should I add a condition on my side to prevent rendering `{{ cart.gateway.getPaymentFormHtml() }}` when the total amount is free (i.e., equal to 0)?

When I use the `freeOrderPaymentStrategy` setting on "_Free orders are processed by the payment gateway_," I get the following error from the Stripe platform:

> _The amount must be greater than or equal to the minimum charge amount allowed for your account and the currency set_ ([https://docs.stripe.com/currencies#minimum-and-maximum-charge-amounts](https://docs.stripe.com/currencies#minimum-and-maximum-charge-amounts)).  
> _If you want to save a Payment Method for future use without an immediate payment, use a Setup Intent instead:_ [https://docs.stripe.com/payments/setup-intents](https://docs.stripe.com/payments/setup-intents).

**Comment by lukeholder** [comment] 2024-09-17 02:23
@romainpoirier We have just released a fix for this in the commerce-stripe plugin, version 5.0.4.3 

It will redirect to the form's successful redirect page if the order is already completed on the initial request.

Thanks!

**Closed as completed by lukeholder** 2024-09-17 02:23 UTC
Labels: bug, commerce5, Craft Commerce

**Comment by romainpoirier** [comment] 2024-09-17 07:44
Thank you for the update!

Is there a way to trigger the redirect *before* the page loads? At the moment, the page first loads and then redirects after being displayed. This may cause some confusion for the user.

Additionally, would it be possible to provide a more detailed description for [this release](https://github.com/craftcms/commerce-stripe/releases)? Currently, it only states _Finish 5.0.4.3_ without referencing this ticket.

**Comment by lukeholder** [comment] 2025-02-04 03:26
@romainpoirier Unfortunately the option must load the stripe form to submit. 

An alternative solution for you would be to create the manual payment gateway and make it the only option if the order value is zero. You could then submit right to that from the previous step without loading the page.

Hope that helps.
