### ISSUE TITLE
Invalid Configuration when creating products not on primary site

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#150] opened 2018-03-27 14:35 UTC
We have multiple sites setup. When I try and create a new product on a non-primary site, I get the following error:

```
yii\base\InvalidConfigException: Invalid product ID: 1414 in /Users/tdavis/sites/hamilton/vendor/craftcms/commerce/src/elements/Variant.php:204
Stack trace:
#0 /Users/tdavis/sites/hamilton/vendor/craftcms/commerce/src/elements/Variant.php(654): craft\commerce\elements\Variant->getProduct()
#1 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Model.php(350): craft\commerce\elements\Variant->beforeValidate()
#2 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Elements.php(377): yii\base\Model->validate()
#3 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Elements.php(1341): craft\services\Elements->saveElement(Object(craft\commerce\elements\Variant), true, false)
#4 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Elements.php(473): craft\services\Elements->_propagateElement(Object(craft\commerce\elements\Variant), false, Array)
#5 /Users/tdavis/sites/hamilton/vendor/craftcms/commerce/src/elements/Product.php(677): craft\services\Elements->saveElement(Object(craft\commerce\elements\Variant), false)
#6 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Elements.php(463): craft\commerce\elements\Product->afterSave(false)
#7 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Elements.php(1341): craft\services\Elements->saveElement(Object(craft\commerce\elements\Product), true, false)
#8 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/services/Elements.php(473): craft\services\Elements->_propagateElement(Object(craft\commerce\elements\Product), true, Array)
#9 /Users/tdavis/sites/hamilton/vendor/craftcms/commerce/src/controllers/ProductsController.php(285): craft\services\Elements->saveElement(Object(craft\commerce\elements\Product))
#10 [internal function]: craft\commerce\controllers\ProductsController->actionSaveProduct()
#11 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Controller.php(74): yii\base\Controller->runAction('save-product', Array)
#14 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-product', Array)
#15 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(237): yii\base\Module->runAction('commerce/produc...', Array)
#16 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(445): craft\web\Application->runAction('commerce/produc...', Array)
#17 /Users/tdavis/sites/hamilton/vendor/craftcms/cms/src/web/Application.php(221): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /Users/tdavis/sites/hamilton/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/tdavis/sites/hamilton/public/index.php(21): yii\base\Application->run()
#20 {main}
```

**Comment by lukeholder** [comment] 2018-03-27 17:24
Hi @davist11, unfortunately, I cannot reproduce. Can you please make sure you are on the latest with `composer update` and then give me steps to reproduce. Can you reproduce on a fresh install? If not can you send me your database to support@craftcommerce.com

**Comment by davist11** [comment] 2018-03-27 18:05
Just did a composer update, so I'm at 6e13e346c67c6faef97440a40625afd6f105556e

Still have the same issue, screen recording: https://drive.google.com/file/d/1M2aRImUYwpypQfmJhGuVg7rmm7AlYqct/view?usp=sharing

DB coming via email

**Comment by lukeholder** [comment] 2018-03-27 18:32
Hi @davist11 I just used your database and tried to reproduce and didn't hit the issue:

screencast: http://jmp.sh/jH9w99h

**Comment by davist11** [comment] 2018-03-27 18:42
Hi Luke, 😄  you added it on the **Hamilton** site. I was getting the error when adding it to the **Laboratory** site.

**Comment by lukeholder** [comment] 2018-03-27 21:45
`composer update` and it should be fixed.

**Closed** 2018-03-27 21:45 UTC
