### ISSUE TITLE
UI for adding Adjustors on Order Edit page should be accessible whether or not the order is Completed

### ISSUE THREAD

**Issue by michaelrog** [craftcms/commerce#1961] opened 2021-01-14 19:07 UTC
The Edit Order screen provides a lovely UI for adding Adjustor lines to an order:

![Add Adjustor UI](https://user-images.githubusercontent.com/102379/104636456-01ff5e80-5669-11eb-98e2-b2ed79cbef34.png)

However, that UI is only accessible when an order is Completed.

Ideally, the _"Add an adjustment"_ button would be visible even if an Order is not completed, so an admin can add a custom Adjustor as needed.

**Comment by michaelrog** [comment] 2021-01-14 19:57
In the same vein... probably worth renaming that Edit link to "Edit Adjustments" —

<img width="956" alt="Screen Shot 2021-01-14 at 1 55 02 PM" src="https://user-images.githubusercontent.com/102379/104642300-5fe37480-5670-11eb-85df-6c69ee47ad3d.png">

If the order doesn't already have adjustments, there's no context to indicate what it does...

**Comment by nfourtythree** [comment] 2021-01-15 08:47
Hi @michaelrog 

Thank you for raising the issue. We have gone ahead and updated the wording of the edit adjustments link.

As for the main request, this is a duplicate of #1907 please post any thoughts/feedback on that issue.

Thanks!

**Closed by nfourtythree** 2021-01-15 08:47 UTC
Labels: New
