### ISSUE TITLE
Promoted products and variants not added to cart

### ISSUE THREAD

**Issue by mdunbavan** [craftcms/commerce#2219] opened 2021-06-22 09:12 UTC
**Description**
A client has got a sale approaching and we have hit an issue where the sale item is not adding to cart. We get the cart success message but the actual lineItems array does not get anything added to it. Some example of what is returned from ajax response:

```
cart: {number: "e6161773e7419c3c2df52b3bc1ee1573", reference: null, couponCode: null, isCompleted: false,…}
adjustmentSubtotal: 0
adjustmentSubtotalAsCurrency: "£0.00"
adjustmentsTotal: 0
adjustmentsTotalAsCurrency: "£0.00"
archived: false
availableShippingMethodOptions: []
availableShippingMethods: []
billingAddressId: null
billingSameAsShipping: false
body: null
brexitDisclaimerCheckbox: null
cancelUrl: null
consignmentRef: null
contentId: "1997783"
couponCode: null
courierCompany: {editable: false, groupId: 9, elementType: "craft\elements\Category", contentTable: "{{%content}}",…}
currency: "GBP"
customerId: 6114588
customerLinkHtml: ""
dateAuthorized: null
dateCreated: {date: "6/22/2021", time: "9:00 AM"}
dateDeleted: null
dateOrdered: null
datePaid: null
dateUpdated: {date: "6/22/2021", time: "9:00 AM"}
deliveryDate: null
draftId: null
email: null
enabled: true
estimatedBillingAddressId: null
estimatedBillingSameAsShipping: false
estimatedShippingAddressId: null
fieldLayoutId: 1911
gatewayId: 5
id: 2171379
isCompleted: false
isOnEmailNewsletter: null
isPaid: false
itemSubtotal: 0
itemSubtotalAsCurrency: "£0.00"
itemTotal: 0
itemTotalAsCurrency: "£0.00"
lastIp: "2a00:23c8:4c8e:7001:3105:4e9e:2d27:5e62"
lineItems: []
makePrimaryBillingAddress: null
makePrimaryShippingAddress: null
message: null
notices: []
number: "e6161773e7419c3c2df52b3bc1ee1573"
orderAdjustments: []
orderLanguage: "en-US"
orderSiteId: 1
orderStatusHtml: ""
orderStatusId: null
origin: "web"
outstandingBalance: 0
outstandingBalanceAsCurrency: "£0.00"
paidStatus: "unpaid"
paidStatusHtml: "<span class=\"commerceStatusLabel\"><span class=\"status red\"></span> Unpaid</span>"
paymentAmount: 0
paymentAmountAsCurrency: "£0.00"
paymentCurrency: "GBP"
paymentSourceId: null
recalculationMode: "all"
ref: null
reference: null
registerUserOnOrderComplete: null
returnUrl: null
revisionId: null
shippingAddressId: null
shippingMethodHandle: null
shippingMethodName: null
shippingSameAsBilling: false
shortNumber: "e616177"
siteId: 1
siteSettingsId: 2171376
slug: null
status: "enabled"
storedItemSubtotal: null
storedItemSubtotalAsCurrency: "£0.00"
storedItemTotal: null
storedItemTotalAsCurrency: "£0.00"
storedTotalDiscount: null
storedTotalDiscountAsCurrency: "£0.00"
storedTotalPaid: null
storedTotalPaidAsCurrency: "£0.00"
storedTotalPrice: null
storedTotalPriceAsCurrency: "£0.00"
storedTotalShippingCost: null
storedTotalShippingCostAsCurrency: "£0.00"
storedTotalTax: null
storedTotalTaxAsCurrency: "£0.00"
storedTotalTaxIncluded: null
storedTotalTaxIncludedAsCurrency: "£0.00"
structureId: null
tempId: null
title: null
total: 0
totalAsCurrency: "£0.00"
totalDiscount: 0
totalDiscountAsCurrency: "£0.00"
totalPaid: 0
totalPaidAsCurrency: "£0.00"
totalPrice: 0
totalPriceAsCurrency: "£0.00"
totalQty: 0
totalSaleAmount: 0
totalSaleAmountAsCurrency: "£0.00"
totalShippingCost: 0
totalShippingCostAsCurrency: "£0.00"
totalTax: 0
totalTaxAsCurrency: "£0.00"
totalTaxIncluded: 0
totalTaxIncludedAsCurrency: "£0.00"
totalTaxablePrice: 0
totalTaxablePriceAsCurrency: "£0.00"
totalWeight: 0
trackingLink: null
trashed: false
uid: "be1e28cc-f140-4013-9f40-03e646bb4976"
uri: null
url: null
message: "Cart updated."
success: true
```

**To Reproduce**
How, and what happened?
1. In the CP, create a sale inside Craft Commerce and apply to the purchaseable or the category you require.
2. Next go to the target product and check it has a related sale then hit save on that product.
3. Go to the promoted product and try adding to the basket, the success message comes up but nothing is in the cart.
4. Check the log and no errors occur.

**Expected behavior**
The product should add to the cart as it does without the sale applied to it. It seems like the sale is what is blocking the action from actually adding the the basket.

**Additional info**

PHP version | 7.3.27
Linux 4.15.0-22-generic
MySQL 5.7.33
Imagick 3.4.4 (ImageMagick 6.9.7-4)
Craft Pro 3.6.16
Craft Commerce 3.3.3

**Additional context**
Live product url here:
https://www.viaduct.co.uk/montis-furniture-otis-2-seater-sofa

Thanks,
Mark

**Comment by lukeholder** [comment] 2021-06-22 09:56
@mdunbavan is the product marked as available for purchase. Could you email support@craftcms.com with your  DB dump, composer.json, composer.lock, and screenshot of the product edit page for that product. Thanks.

**Comment by mdunbavan** [comment] 2021-06-22 13:27
@lukeholder yes the product is available.

I am sending it all over now.

**Comment by mdunbavan** [comment] 2021-06-22 13:35
Screengrabs are here btw.
![screencapture-viaduct-co-uk-admin-commerce-products-sofas-2115154-otis-3-seater-sofa-2021-06-22-14_26_19](https://user-images.githubusercontent.com/671281/122934054-16a5f800-d367-11eb-8938-654e86108ace.png)
![screencapture-viaduct-co-uk-admin-commerce-products-sofas-2115154-otis-3-seater-sofa-2021-06-22-14_25_49](https://user-images.githubusercontent.com/671281/122934084-1c9bd900-d367-11eb-9bbf-f4cda420d1ca.png)
![screencapture-viaduct-co-uk-admin-commerce-products-sofas-2115154-otis-3-seater-sofa-2021-06-22-14_25_05](https://user-images.githubusercontent.com/671281/122934087-1c9bd900-d367-11eb-9e7f-bb670d4424e1.png)

**Comment by lukeholder** [comment] 2021-07-01 12:07
Issue was caused by submitting a blank `puchasableId` to the update cart controller due to a front end code bug.

**Closed by lukeholder** 2021-07-01 12:07 UTC
Labels: ℹ️ status: need more info
