### ISSUE TITLE
Order adjustment error preventing order being marked as complete.

### ISSUE THREAD

**Issue by samhibberd** [craftcms/commerce#2040] opened 2021-03-09 00:20 UTC
**Description**
Using a built in discount adjuster, in the form of a coupon code (with no code) applied to a specific member group. On processing the payment, the payment is successful but the following exception is thrown when trying to mark the order as complete. Subsequently accessing the order in the cp and trying to manually Mark as complete, produces the same exception:

> No order Adjustment exists with the ID “70262”

- Debugging the `_saveAdjustments()` method on the Order element, shows that the `saveAdjustmentMethod()` creates a valid adjuster on the first run, returns true for the `->save(false)`, gets the id and updates the adjuster model. 
- Subsequent runs use the id that was set, but the exception is thrown because the method looks for a record by id, tat is not set, suggesting no data is committed to the database.
- The id is incrementing, suggesting that something could be going wrong at the point of writing to the db? Or might it be getting removed?

I have got custom order events in my module, but the issue still exists when these are disabled.

**Additional info**
- Craft version: 3.6.9
- Commerce version: 3.2.17
- PHP version: 7.4
- Database driver & version: MariaDB 10.5.5 locally and MariaDB 10.1 on the production server

> 18 craft\commerce\services\OrderAdjustments:saveOrderAdjustment
> 17 craft\commerce\elements\Order:_saveAdjustments
> 16 craft\commerce\elements\Order:afterSave
> 15 craft\services\Elements:_saveElementInternal
> 14 craft\services\Elements:saveElement
> 13 craft\commerce\elements\Order:markAsComplete
> 12 craft\commerce\controllers\OrdersController:actionSave
> 11 nullcall_user_func_array
> 10 yii\base\InlineAction:runWithParams
> 9 yii\base\Controller:runAction
> 8 craft\web\Controller:runAction
> 7 yii\base\Module:runAction
> 6 craft\web\Application:runAction
> 5 craft\web\Application:_processActionRequest
> 4 craft\web\Application:handleRequest
> 3 yii\base\Application:run
> 2 /Users/samhibberd/Sites/forwardvia.com/web/index.php:21
> 1 null[top]
> OrderAdjustments.php:177

**Comment by lukeholder** [comment] 2021-03-09 03:48
I can't reproduce this. 

Can you send your DB backup, composer.json and composer.lock to support@craftcms.com with steps to reproduce on your site.

Thanks,

**Comment by samhibberd** [comment] 2021-03-09 07:51
Thanks @lukeholder, details sent.

**Comment by samhibberd** [comment] 2021-03-09 21:52
After confirming a bit more detail from the client, looks like the issue initially occurs on a payment with the stripe gateway only when authentication is not required. Stripe PI (Redirect) and PayPal all ok. Payment is taken and order is marked as complete.

Using the stripe gateway and the standard test card 4242 4242 4242 4242 (no auth required) the payment goes through but the exception is thrown and order is not / and can't be marked as complete manually.

**Comment by pdaleramirez** [comment] 2021-03-10 08:45
@samhibberd I am closing this because It is a different issue from the title. Will continue conversation on the ticket.

**Closed by pdaleramirez** 2021-03-10 08:45 UTC
Labels: 🧾 orders
