### ISSUE TITLE
[4.x]: PDF::renderPdfForOrder Pdf Parameter is optional but actually required 

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#3289] opened 2023-10-04 12:13 UTC
### Description

calling renderPdfForOrder manually without predefined Pdf was possible in Commerce 3, now a Pdf object is actually required

### Steps to reproduce

1. call `renderPdfForOrder` with no Pdf object
2. get an error `Call to a member function getRenderLanguage() on null` because while the parameter is optional, it is required in the function https://github.com/craftcms/commerce/blob/4.3.0/src/services/Pdfs.php#L469

```PHP
public function renderPdfForOrder(Order $order, string $option = '', string $templatePath = null, array $variables = [], Pdf $pdf = null): string
{
        // correct check if it is there
	if ($pdf instanceof Pdf) {
		$templatePath = $pdf->templatePath;
	}
        // ... snip ... 
        // null pointer exception, no check
	$pdfLanguage = $pdf->getRenderLanguage($order);
```

### Expected behavior

the function should check if there is a Pdf or not, in case there is no, don't work with a `null` value

### Actual behavior

the function does not check if an optional parameter is passed

### Craft CMS version

4.x

### Craft Commerce version

4.x

**Comment by nfourtythree** [comment] 2023-10-09 09:01
Hi @Anubarak 

I believe this is a duplicate of #2633, have just pushed up a PR to fix that: https://github.com/craftcms/commerce/pull/3292

Please follow along with the progress of this issue there.

Thanks!

**Closed by nfourtythree** 2023-10-09 09:01 UTC
Labels: 🐞 bug, commerce4

**Comment by Anubarak** [comment] 2023-10-09 10:29
Thank you very much

**Comment by nfourtythree** [comment] 2023-10-13 07:03
@Anubarak just as an FYI there has been an update to this issue: https://github.com/craftcms/commerce/issues/2633#issuecomment-1761009185
