### ISSUE TITLE
Allow multiple Promotion Codes per Discount (as per Stripe's implementation)

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#2187] opened 2021-06-04 10:27 UTC
There are currently UI issues around the way Discount codes are handled in the CP. When there are more than a handful of promo codes things become unwieldy. I have also seen another issue logged here where the site is running into memory problems because of the large number of codes generated. This is often caused by issuing personalised discount codes which may all actually apply the same discount.

I'd suggest that Commerce continues to use Discounts, but allows for the creation of multiple codes within that Discount. This means that a single Discount, say 10% off and the other logic, could be created but unique Promotion Codes created within that to trigger that Discount. This should mean less overhead as there are fewer overall Discounts to deal with and it becomes a case of a simple relationship between a Promotion Code and its parent Discount.

It would also then be possible, and in my head simpler, to import pre-generated codes into a single Discount.

This methodology is used by Stripe and works very well. I think it would be a great enhancement to how Commerce handles promotional codes.

**Comment by lukeholder** [comment] 2021-06-07 11:47
Duplicate of https://github.com/craftcms/commerce/issues/1388 We are going to be working on this in an upcoming release.

**Closed by lukeholder** 2021-06-07 11:47 UTC
Labels: New, 💡 enhancement
