### ISSUE TITLE
Commerce problem with variant's their status (Looks like they are disabled but still show front end))

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [craftcms/commerce#926] opened 2019-07-08 08:39 UTC
### Description
Problem with variants their status.
So it seems to me that the getAllVariantsByProductId returns all product variants no matter the status.
So for me front end variants get displayed even if their status is disabled (i can fix it by checking the status front end) however i though i should still report it because it seems to me its buggy as well back end.

![Screenshot 2019-07-08 at 10 24 21](https://user-images.githubusercontent.com/50947605/60794680-94689d00-a16a-11e9-8a1a-dca915269c72.png)

This means the filter does not work when i select enabled it shows all the "disabled items"
And if i choose disabled it shows nothing.
I think this has something to do with multi site.

Thanks in advance,

### Steps to reproduce

1. Make a craft commerce site (multi site be sure to have at least 2)
2. use a product variant field to try to display product variant front end ( and play with their status).

### Additional info

- Craft version: 3.1.31
- PHP version: 7.2.10
- Plugins & versions: Commerce (2.1.7)

**Comment by bob-pixeldeluxe** [comment] 2019-08-07 15:23
@lukeholder 

Any progress?

Thank you.

**Comment by lukeholder** [comment] 2019-08-14 06:01
Yes, I was unable to reproduce. Video: https://jmp.sh/FJ8cmkm

As for `getAllVariantsByProductId` yes it does return all variants regardless of status. so `product.variants` returns all variants. If you want to only return variants that are enabled use a variant query with: `{% for variant in craft.variants.product(product).all() %}`. Let me know if that helps on the front-end.

**Comment by tim-pixeldeluxe** [comment] 2019-08-14 08:18
@lukeholder I was able to reproduce this on multiple Craft Commerce installs.

Craft version: 3.2.8
Commerce version: 2.1.10

Steps to reproduce:
1. Create a product with variants
2. Disable the product
3. Create a Commerce Variants field
4. Open the field modal

It will display all variants as the variant elements itself are enabled but it shows the status of the product. When I enable the product I still see the variants but now they have an enabled status.

**Comment by tim-pixeldeluxe** [comment] 2019-08-14 08:51
Was able to reproduce this on a env with only Commerce installed.

Craft version: 3.2.10
Commerce version: 2.1.11

![Schermafbeelding 2019-08-14 om 10 50 29](https://user-images.githubusercontent.com/46448696/63007674-653bfe80-be81-11e9-8a58-85c9d7874f25.png)

**Comment by tim-pixeldeluxe** [comment] 2019-08-14 13:24
Another update: I've been looking through the source and I think I know why this is happening. Variants override the getStatus() function and return `STATUS_DISABLED` when their product is disabled. The element indexes controller probably queries the DB directly and since its disabled there its included in the query results. The modal than prints these results but since it is using getStatus() it will show the variant as disabled.

**Comment by lukeholder** [comment] 2019-08-15 03:59
Looks like you have found it. Thinking of a solution now.

**Comment by lukeholder** [comment] 2019-08-28 08:43
Will push a fix for this later today.

**Comment by tim-pixeldeluxe** [comment] 2019-08-28 08:49
> Will push a fix for this later today.

Thank you!

**Comment by lukeholder** [comment] 2019-08-29 06:12
- Variant status is no longer overriden by the product status in `Variant::getStatus()`
- Product status and Variant status together define if the variant is available for sale (which was the original intent of having the variant status check the product status before we introduced `isAvailable`)

**Closed** 2019-08-29 06:11 UTC
Labels: bug
