### ISSUE TITLE
Http\Adapter\Guzzle6\Client' not found 

### ISSUE THREAD

**Issue by pepsDev** [craftcms/commerce#2124] opened 2021-05-05 08:42 UTC
**Description**
Can't open Orders in CP after upgrading the Mollie-Plugin craftcms/commerce-mollie 3.0.

**Error**
`Class 'Http\Adapter\Guzzle6\Client' not found`

**Additional info**
Craft version: 3.6.12
Commerce version: 3.3.0
PHP version: 7.4.18

**Comment by lukeholder** [comment] 2021-05-05 09:23
Duplicate of https://github.com/craftcms/commerce-mollie/issues/35

Responding there.

**Closed by lukeholder** 2021-05-05 09:23 UTC
Labels: New
