### ISSUE TITLE
Save new product as a draft

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#219] opened 2018-03-28 18:26 UTC
> Created by: Anonymous ([andy@brink.uk](andy@brink.uk)) on 2016/03/15 18:41:10 +0000
Votes at time of UserVoice import: 4

------
When entering new products allow 'save as a draft' which saves progress without the need to complete all required fields. This would be most helpful!

**Comment by lukeholder** [comment] 2020-02-13 21:10
Duplicate of https://github.com/craftcms/commerce/issues/1137

**Closed by lukeholder** 2020-02-13 21:10 UTC
Labels: 👚 products, 💡 enhancement
