### ISSUE TITLE
Better clarity around "Times Coupon Used"

### ISSUE THREAD

**Issue by engram-design** [craftcms/commerce#685] opened 2019-02-05 19:54 UTC
Here's a valid complaint from a client using many coupon codes. They'd like to be able to see how many times it's been used. Currently, there's a column in Discounts for "Times Used", but is always 0. As the field instructions state - "How many times this coupon has been used, if a total coupon usage limit has been set."

What I would propose is to have this record (or query orders with a coupon) all coupon code usage, whether the total usage limit has been set or not.

Alternatively, another option would be to include it as an additional column on the orders index screen, so you don't have to drill into each order to see when a coupon has been used.

In the instance of this client, its a special coupon (with a little bit of custom code) that restricts it to only first-time orders, so it's really useful to their business to know identify new customers.

Thoughts?

**Comment by aarmitage** [comment] 2019-07-25 09:53
Adding our voice to this - this has come up before but surfaced again with a new commerce launch.

> What I would propose is to have this record (or query orders with a coupon) all coupon code usage, whether the total usage limit has been set or not.

Agree with this suggestion.

**Comment by matt-adigital** [comment] 2019-07-25 09:55
Looking at the code it should just be a case of removing the conditional on [line 544](https://github.com/craftcms/commerce/blob/master/src/services/Discounts.php#L544) of the discounts service file. The conditional on [line 205](https://github.com/craftcms/commerce/blob/master/src/services/Discounts.php#L205) can remain unchanged.

This would mean that the usage would then be tracked for all discounts regardless of limits and make much more sense for the cms users when displayed in the control panel.

Please can this change be made soon as it is confusing for clients when they see that a discount coupon code has been used but the Times Used value on the discounts index page is still showing as zero. Thank you.

**Comment by lukeholder** [comment] 2019-10-11 01:47
Duplicate of #521

**Closed by lukeholder** 2019-10-11 01:47 UTC
Labels: :loudspeaker: promotions, 💡 enhancement
