### ISSUE TITLE
[3.x]: Multiple orders when cart cart.markAsComplete()

### ISSUE THREAD

**Issue by anchovy** [craftcms/commerce#2870] opened 2022-06-29 00:42 UTC
### Description
I'm using sprig and a template to automatically add a Verbb Event ticket ($0.00) to the cart and complete the order. 
For some reason - this is generating around hundreds of completed orders per call, rather than just the one?

### Steps to reproduce
These are simplified - but still produce the same resulte.
1. Using verbb events - set up an event with a ticket priced at $0.00
2. get the purchasable ID fro the ticket.
3. add the following code to a template:
```            {# get the cart or create a new cart #}
            {% set cart = cart is not defined ? craft.commerce.carts.cart(true) : cart %}

            {# Generate the line item if it's not already in the cart #}
            {% set lineItem = craft.commerce.lineitems.resolveLineItem(cart.id, 39206) %}
            
            {# add the line itme #}
            {% do cart.addLineItem(lineItem) %}
            
            {# Complete the order #}
            {% do cart.markAsComplete() %}
```
4. load the page.

### Expected behavior
1 completed order

### Actual behavior
hundreds of completed orders
![image](https://user-images.githubusercontent.com/599005/176326952-14d599f0-1b10-417f-a33e-908831807b53.png)

NB - If I omit the last line `{% do cart.markAsComplete() %}` then in commerce I've got the one active cart but the line items is empty.

### Craft CMS version

Craft Pro 3.7.45.1

### Craft Commerce version

3.4.15

### PHP version

8.0.8

### Operating system and version

MySQL 8.0.27

### Database type and version

MySQL 8.0.27

### Image driver and version

Imagick @PACKAGE_VERSION@ (ImageMagick 6.9.6-2)

### Installed plugins and versions

Amazon S3	1.3.0
Asset Usage	2.2.1
AsyncQueue	2.3.0
Child Me!	1.3.1
Colour Swatches	1.6.0
Control Panel Nav	3.0.17
CP Field Inspect	1.4.4
Craft Commerce	3.4.15
Craft Slugify	1.0.1
Embedded Assets	2.11.0
Enupal Snapshot	1.2.9
Events	1.4.20
Feed Me	4.5.3
Field Manager	2.2.4
Forms (Freeform)	3.13.13
Imgix	2.1.0
LJ Dynamic Fields	3.0.12
Navigation	1.4.26
Payment Express for Craft Commerce 2	1.5.0
PDF Transform	1.0.7
Phone Number	1.5.0
Rollbar	1.3.0
Smith	1.2.3
Sprig	1.13.0
Super Table	2.7.2
Template Select	2.0.2
Twigpack	1.2.17
Typed link field	1.0.25
User Group Field	1.0.4
Vizy	1.0.15
Width Fieldtype	1.1.0

**Comment by anchovy** [comment] 2022-06-29 02:04
**NB** - the CP goes away after a while as well and I get the install screen - I think whatever the bug is is looping adding more orders and tying up all the DB connections/memory.

**Comment by nfourtythree** [comment] 2022-07-12 07:15
Hi @anchovy 

I would suggest maybe moving this logic to a custom module. You mentioned using Sprig and doing this in the template seems like there are more variables at play.

It is tough to know what is actually going on without the full context of the project. But it is certainly possible to programmatically complete an order.

Thanks.

**Comment by lukeholder** [comment] 2022-07-22 02:51
This is definitely related to calling `order.markAsComplete` in a template. New orders will be zero price, so likely you twig code is the cause of the looping creation and completion of orders.

**Closed by lukeholder** 2022-07-22 02:51 UTC
Labels: ℹ️ status: need more info, commerce3
