### ISSUE TITLE
Add the ability to merge customers

### ISSUE THREAD

**Issue by Anubarak** [craftcms/commerce#1804] opened 2020-10-23 08:18 UTC
**What are you trying to do?**
Even after many complains from my side my client wanted to create a login without double-opt-in and without the requirement to confirm the email address.

As you can expect many users entered the wrong e-mail, registered twice or even more times which leads to trouble and confusion because for this system every user needs to be "unique" (users receive a rfid cart that is bound to their account)

Because of this my client wants a mechanic to merge those users/customers into one. While I can write this logic on my own I would need to adjust many things in case you change certain components, DB tables, logic and so on. So it would be really nice if there was a way to gracefully merge two customers into one and delete the other.

**What's your proposed solution?**
What I'm talking about is especially:

- orders -> change the customerId from the old to the new
- addresses -> move all addresses to the new
- all other things that I don't have in my mind right now

then delete the old customer.

**Comment by lukeholder** [comment] 2020-10-27 05:17
Duplicate of https://github.com/craftcms/commerce/issues/1109

**Closed by lukeholder** 2020-10-27 05:17 UTC
Labels: 👤 customers, 💡 enhancement
