### ISSUE TITLE
Conditional Fields

### ISSUE THREAD

**Issue by andris-sevcenko** [craftcms/commerce#152] opened 2018-03-28 18:13 UTC
> Created by: Enrico ([enrico@welance.com](enrico@welance.com)) on 2018/03/23 16:24:42 +0000
Votes at time of UserVoice import: 4

------
Allow admins to make conditions to show/hide fields.

As discussed here: https://craftcms.stackexchange.com/questions/8574/conditional-field-layout-hiding-or-showing-fields-based-on-another-field

**Comment by lukeholder** [comment] 2018-03-28 18:27
Should be a Craft issue. Closed as duplicate of https://github.com/craftcms/cms/issues/805

**Closed by lukeholder** 2018-03-28 18:27 UTC
