### ISSUE TITLE
Exception is thrown when deleting a product

### ISSUE THREAD

**Issue by benjamindavid** [craftcms/commerce#358] opened 2018-05-28 08:46 UTC
### Description

A “Variant is missing its product” exception is thrown when deleting a product.

```
2018-05-28 09:19:19 [::1][1][-][trace][yii\db\Transaction::rollBack] Roll back transaction
2018-05-28 09:19:19 [::1][1][-][error][yii\base\InvalidConfigException] yii\base\InvalidConfigException: Variant is missing its product in /Users/ben/Sites/plugins3/vendor/craftcms/commerce/src/elements/Variant.php:207
Stack trace:
#0 /Users/ben/Sites/plugins3/vendor/craftcms/commerce/src/elements/Variant.php(191): craft\commerce\elements\Variant->getProduct()
#1 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/base/Element.php(1967): craft\commerce\elements\Variant->getFieldLayout()
#2 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/base/Element.php(1823): craft\base\Element->fieldLayoutFields()
#3 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/services/Elements.php(921): craft\base\Element->beforeDelete()
#4 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/services/Elements.php(901): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Variant))
#5 /Users/ben/Sites/plugins3/vendor/craftcms/commerce/src/elements/Product.php(712): craft\services\Elements->deleteElementById(242, 'craft\\commerce\\...')
#6 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/services/Elements.php(961): craft\commerce\elements\Product->afterDelete()
#7 /Users/ben/Sites/plugins3/vendor/craftcms/commerce/src/elements/actions/DeleteProduct.php(37): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Product))
#8 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/controllers/ElementIndexesController.php(198): craft\commerce\elements\actions\DeleteProduct->performAction(Object(craft\commerce\elements\db\ProductQuery))
#9 [internal function]: craft\controllers\ElementIndexesController->actionPerformAction()
#10 /Users/ben/Sites/plugins3/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /Users/ben/Sites/plugins3/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('perform-action', Array)
#13 /Users/ben/Sites/plugins3/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('perform-action', Array)
#14 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/web/Application.php(273): yii\base\Module->runAction('element-indexes...', Array)
#15 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/web/Application.php(521): craft\web\Application->runAction('element-indexes...', Array)
#16 /Users/ben/Sites/plugins3/vendor/craftcms/cms/src/web/Application.php(257): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /Users/ben/Sites/plugins3/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/ben/Sites/plugins3/web/index.php(21): yii\base\Application->run()
#19 {main}
```

### Steps to reproduce

1. Go to the products index page
2. Check a product and delete it

### Additional info

- Craft version: 3.0.9
- PHP version: 7.2.1
- Database driver & version: MySQL 5.6.38
- Plugins & versions: Commerce 2.0.0-beta.4.1

**Comment by lukeholder** [comment] 2018-07-25 05:43
Duplicate of #417

**Closed by lukeholder** 2018-07-25 05:43 UTC
Labels: bug

**Comment by engram-design** [comment] 2018-08-17 01:47
I can confirm this is a separate issue to #417 and only for the default seeded products. Once you go into each product and save, you're then able to delete products. Creating new products on the installation and deleting them is fine.

Seems like its just an issue with the seeded products?

**Comment by ScoutsOut** [comment] 2018-08-19 02:45
Thank you @engram-design - that worked for me! 👍 👍

**Comment by bymayo** [comment] 2018-11-07 10:43
I simply selected all in the table view, changed the status to 'Disabled' then it saved the status on all products. Then select all again and choosing 'Delete' worked.

This only seems to be an issue with the product examples installed via Commerce 2.
