### ISSUE TITLE
Cannot refund 'authorize' transactions

### ISSUE THREAD

**Issue by stolat** [craftcms/commerce#1308] opened 2020-02-26 19:53 UTC
### Description
We need to use Authorize only with the Stripe gateway.  Admins will review orders prior to capturing payment.  If an order is not approved we need to cancel the Authorize transactions rather than waiting 7 days for it to expire.  With Stripe this can be done with a Refund; but the button is not displayed.  I would also think transaction.canRefund() should return TRUE for these types of transactions.

### Steps to reproduce

1. Set Stripe gateway to Authorize only
2. Create payment.
3. View transactions in CP; refund/cancel button is not available.  canRefund() also returns false.

### Additional info

- Craft version: 3.4.8
- PHP version: 7.1.32
- Database driver & version: MySQL 5.7.16
- Plugins & versions: Commerce 3.0.11, Stripe for Commerce 2.2.3

**Comment by joshuabaker** [comment] 2020-03-04 16:13
#611

**Comment by lukeholder** [comment] 2020-04-01 06:41
Duplicate of #611

**Closed by lukeholder** 2020-04-01 06:41 UTC
Labels: 💡 enhancement, 💳 payments
