### ISSUE TITLE
Saving an existing product clears out the stock field

### ISSUE THREAD

**Issue by jsunsawyer** [craftcms/commerce#1289] opened 2020-02-20 20:05 UTC
### Description
Whenever I save a product (no changes even have to be made), the `stock` field value is cleared out, forcing me to re-enter a value to save.

With an existing value of `1`, saving a product results in the following.

![Screen Shot 2020-02-20 at 12 01 26 PM](https://user-images.githubusercontent.com/1007191/74973938-37f47e00-53d9-11ea-8680-05e156b1c515.png)

### Additional info

- Craft version: 3.4.6.1
- Commerce version: 3.0.10

**Comment by nfourtythree** [comment] 2020-02-20 22:27
This is a duplicate of #1288

**Closed by nfourtythree** 2020-02-20 22:27 UTC

**Comment by jsunsawyer** [comment] 2020-02-20 22:31
Ah nice, didn't see that one. Updating to that dev release fixed my issue.
