### ISSUE TITLE
Server error when fetching cart using javascript

### ISSUE THREAD

**Issue by DiederikVanHoorebeke** [craftcms/commerce#477] opened 2018-09-04 11:19 UTC
### Description
When logged in as admin, and when devMode is enabled, fetching `/actions/commerce/cart/get-cart` triggers a server error:
```TypeError: Argument 1 passed to craft\commerce\services\Countries::getCountryById() must be of the type integer, null given, called in /craft/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1619 and defined in /craft/vendor/craftcms/commerce/src/services/Countries.php:60```

This error does not occur when not logged in.

### Steps to reproduce

1. Log in as admin and make sure devMode is enabled.
2. Fetch the cart using the `/commerce/cart/get-cart` action.

### Additional info

- Craft version: 3.0.22
- PHP version: 7.2.9
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Commerce 2.0.0-beta.8.1

**Comment by lukeholder** [comment] 2018-09-05 03:56
I am unable to reproduce. Logged in and not. 

Are you calling `craft.commerce.countries.getCountryById()` anywhere in your templates?

**Comment by DiederikVanHoorebeke** [comment] 2018-09-05 07:42
@lukeholder it seems there was indeed an error in a template where `getCountryById` is being used. The weird thing though, it's in the order pdf template. Fixing that, fixed the issue.

But, on the other hand, I see no reason that an error in the pdf template should cause the `get-cart` action to fail.

**Comment by lukeholder** [comment] 2018-09-05 08:39
Looks like we are rendering the PDF when generating the PDF link that gets placed in the order's json response under `pdfUrl`. We will fix this.

**Comment by lukeholder** [comment] 2018-09-05 08:39
Fixed in 0edc565fff33818bee7b369c01b671816

**Closed by lukeholder** 2018-09-05 08:39 UTC
