### ISSUE TITLE
Downloading multiple order PDFs on order list as single large PDF file

### ISSUE THREAD

**Issue by piotrpog** [craftcms/commerce#2156] opened 2021-05-26 07:41 UTC
It would be usefull if there was an option to download multiple order PDFs on order list not as an ZIP file, but one large PDFs with content of every single PDF budled into it.

**Comment by lukeholder** [comment] 2021-05-26 13:12
Will go ahead and add this for the next release. Thanks.

**Comment by lukeholder** [comment] 2021-05-26 13:27
Duplicate of https://github.com/craftcms/commerce/issues/1785

**Closed by lukeholder** 2021-05-26 13:27 UTC
Labels: 💡 enhancement, 📬 emails
