### ISSUE TITLE
Coupon / Discount Code field for subscriptions

### ISSUE THREAD

**Issue by astuteo** [craftcms/commerce#696] opened 2019-02-07 22:37 UTC
I'm not sure what's involved on the Craft side of things, but it would be very nice to see the coupon code field available for subscriptions. It's an important marketing tool for subscription-based services, especially new ones. I believe this is already available on Stripe's end for subscriptions.

**Comment by lukeholder** [comment] 2019-02-09 08:02
Yes, this is in the works. Thanks for submitting.

**Comment by lukeholder** [comment] 2019-02-19 15:23
Duplicate of #295

**Closed by lukeholder** 2019-02-19 15:23 UTC
Labels: enhancement
