### ISSUE TITLE
[5.x]: Allow BCC'd Recipient, Email Subject, and Reply-To in Commerce Email Settings to Use Environment Variables

### ISSUE THREAD

**Issue by romainpoirier** [craftcms/commerce#3823] opened 2024-12-19 08:39 UTC
### Description  
In the Commerce Settings > Emails section, only the **Status Email Address** and **From Name** can currently be set as environment variables.  

On my staging environment, I need the **BCC’d Recipient** to differ from production. However, since the `/admin/commerce/settings/emails/primary/1` section is not accessible when `CRAFT_ALLOW_ADMIN_CHANGES=false` (which is the expected setting for staging), I cannot modify this value.  

Why does Craft Commerce not allow additional email options, such as **BCC’d Recipient**, **Email Subject**, and **Reply-To**, to be defined as environment variables? Is this an oversight?  

Is there an alternative solution, such as defining these settings via `config/commerce.php`? If yes, what are the exact keys to use? The **BCC’d Recipient** option, for instance, is not documented here: [Commerce 5.x Configuration](https://craftcms.com/docs/commerce/5.x/configure.html)

In my case, being able to set **BCC’d Recipient** as an environment variable is crucial. However, having the ability to set **Email Subject** and **Reply-To** in the same way would be highly beneficial.  

### Steps to reproduce  
1. Set up a staging environment with `CRAFT_ALLOW_ADMIN_CHANGES=false`.  
2. Attempt to configure the **BCC’d Recipient** for Commerce Emails to differ from production.  
3. Notice that this value cannot be set via environment variables or the `config/commerce.php` file.  

### Expected behavior  
The **BCC’d Recipient**, **Email Subject**, and **Reply-To** fields should support the use of environment variables for easier configuration across environments (staging, production, etc.).  

### Actual behavior  
These fields cannot be defined as environment variables, and there is no documented alternative to set them via the configuration file. This limits flexibility, especially in non-production environments where admin changes are restricted.

### Craft CMS version

5.5.3 

### Craft Commerce version

5.2.6

### Installed plugins and versions

-

**Comment by lukeholder** [comment] 2024-12-27 05:25
Duplicate of **https://github.com/craftcms/commerce/issues/3823**

This has been added to the next release of Commerce (5.3)

**Closed as completed by lukeholder** 2024-12-27 05:25 UTC
Labels: bug, commerce5, Craft Commerce
