### ISSUE TITLE
Remove shipping costs for matching products only does not work

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#1384] opened 2020-04-15 12:44 UTC
### Description
I created a new discount, added some variants and checked this option:
"Remove shipping costs for matching products only"
The shipping for these products should be set to zero. 
Instead, it removed the entire order shipping costs

### Additional info

- Craft version: 3.3.15
- Commerce version: 2.2.7

**Comment by nfourtythree** [comment] 2020-04-15 13:34
Hi @Sam-Black-0013 

I am unable to replicate this.

Here is my cart:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/RBuv1nZL/Screenshot%202020-04-15%20at%2014.31.07.png?v=5c8dc4f5a7aa743fb7e39d88e93f85cb)

As you can see both items have shipping costs "SHIPPING Videographic Distribution - $5" and there is also a base cost "Videographic Distribution - $10".

I then apply my discount which is set to "Remove shipping costs for matching products only", that product is "Breaking Bad - Season 1"

The rest is that the shipping costs have been removed:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/RBuv1nkK/Screenshot%202020-04-15%20at%2014.33.33.png?v=56c9631519b6063372e63412a1f341c6)

Please let me know if you have any further info on how to replicate what you are seeing.

Thanks.

**Comment by nfourtythree** [comment] 2021-01-07 09:33
Hi @Sam-Black-0013 

We believe this is a duplicate of #1329

Please add any extra information/thoughts over on that issue.

Thanks!

**Closed by nfourtythree** 2021-01-07 09:33 UTC
Labels: ℹ️ status: need more info
