### ISSUE TITLE
Add a 3rd Level to tax and shipping zones for country or zip code range

### ISSUE THREAD

**Issue by jacksutherland** [craftcms/commerce#366] opened 2018-06-04 19:18 UTC
### Description
If you live in a destination tax state, you are required to collect tax per the county you are shipping to. However from what I can tell Craft Commerce offers no means to do this. It has a Country tax and State tax, but no County option. My client is worried about the legality behind not collecting the appropriate sales tax. Is there a way to do this? If not can it be a feature upgrade? Thanks.

### Steps to reproduce

1. Login to Commerce 
2. Navigate to Commerce > Settings > Tax Zone
3. Country and State are options but not County

### Additional info

- Craft version: Craft 2 Commerce 1
- PHP version: 7
- Database driver & version: MySQL
- Plugins & versions: Commerce 1

**Comment by AugustMiller** [comment] 2018-06-14 19:05
Our one client who needed to collect County tax decided they would absorb this tax, themselves.

My understanding is that this tax is often just for in-county sales (i.e. both the seller and buyer are located in the same region)? For the time being, you might consider creating a plugin that supplies an `Adjuster` based on a custom field? It could be as simple as a new "I am a resident of _County_" checkbox (or a drop-down), which applies a percentage-based adjustment to the order.

I can't speak to the actual roadmap for Commerce, but I suspect including county relationships will be a ways off (although it might be architecturally similar to Countries + States, as they are now), since it applies to such a narrow group of merchants… the tools do exist to do what you want, though!

**Comment by oadslug** [comment] 2018-09-27 20:37
I have client that would benefit from this also. One relatively easy way to deal with this, might be to include zip codes within state tax zones, with a field for a comma delimited string or array of zip codes. A tax zone is not always a perfect match to zip codes (as there are rare occasions where a zip code crosses tax zone boundaries), but it's pretty close, and would use data already available via shippingAddress. The only thing to consider would be to strip out zip code suffix if defined ( i.e. 94117-0004 would become just 94117) — perhaps do a zipCode 'contains' vs zip code 'is'.

**Comment by lukeholder** [comment] 2018-11-26 14:33
Closed as duplicate of https://github.com/craftcms/commerce/issues/366

**Closed by lukeholder** 2018-11-26 14:33 UTC
Labels: enhancement
