### ISSUE TITLE
Disabled products don't affect those variants

### ISSUE THREAD

**Issue by abuerin** [craftcms/commerce#2207] opened 2021-06-15 18:11 UTC
**Description**

In one project, we use `craft.variants` to loop over all variants. 
Now we have disabled many products, but the variants of the disabled products still give us an output.

```
{% for item in craft.variants %}
	{{ item.title }}
{% endfor %}
```

**Comment by nfourtythree** [comment] 2021-06-15 18:49
Hi @abuerin 

This is actually a duplicate of #2015 

It due to variants being elements in their own right. As mentioned in the other issue this is something that we are discussing internally as to what the best solution would be.

For moment you can update your code to the following to get things working nicely:

```twig
{% for item in craft.variants.hasProduct({ status: 'live' }).all() %}
	{{ item.title }}
{% endfor %}
```

This will ensure that only variants with `live` products are returned.

Thanks!

**Closed by nfourtythree** 2021-06-15 18:49 UTC

**Comment by abuerin** [comment] 2021-06-16 21:26
Okay, thanks. This way it works fine.
