### ISSUE TITLE
Strange behavior in when adding multiple products to cart while logging in and out

### ISSUE THREAD

**Issue by WHITE-developer** [craftcms/commerce#2585] opened 2021-10-14 07:05 UTC
### Description
When logging in and out while shopping, the content of the cart shuffles. This strange behavior happens on different shops.
(and yes, apparently customers are shopping like this)

### Steps to reproduce (also see video)

1. Log in
2. Add product A in cart
3. Log out
4. Add product B in cart
5. Log in again, then product A is in cart
6. Log in and log out again, product A stays in cart
7. Remove product A from cart
8. Log in and then product B in suddenly in the cart
9. Then remove product B and the cart is empty and stays empty

https://s3.eu-central-1.amazonaws.com/static.kindermodehuis.nl/assets/Temporary/2021-10-08-15-44-31.mp4

### What we like to see

1. Log in
2. Add product A to cart
3. Log out
4. Add product B to cart
5. Log in and we'd expect product A and B in cart
6. Log out and both product should stay in cart

### Additional info

- Craft CMS version: 3.5.19 to 3.7.10
- Craft Commerce version: 3.2.14.1 to 3.4.2
- PHP version: 7.4
- Database driver & version: MySQL 5.7
- Plugins & versions: Differs on different websites

**Comment by nfourtythree** [comment] 2021-10-14 07:58
Hi @WHITE-developer 

What you are seeing here is expected behaviour. At the moment there is no functionality for merging carts when logging into a user account. I have just created a [feature request](https://github.com/craftcms/commerce/discussions/2586) for this.

When logging into a user account the [login handler](https://github.com/craftcms/commerce/blob/develop/src/services/Customers.php#L396-L408) is triggered, this, in turn, tries to [restore a previous cart](https://github.com/craftcms/commerce/blob/develop/src/services/Customers.php#L396-L408) for the user that has just logged in.

As you will be able to see from the code there are certain criteria that must be met to restore a cart.

There must be a user, the current cart in session must have no items in it and then the code tries to retrieve a cart that has items and is related to the user. If all those things are true then the cart that is found will be added to the session.

It is also worth noting that when you log out, the system ["forgets" the cart in the session](https://github.com/craftcms/commerce/blob/develop/src/services/Customers.php#L523-L528) to prevent an unauthenticated guest from seeing any personal data.

With all the above information I believe this explains what you are seeing. Just as a note the steps you outlined and the video shows slightly different things, so the below is based on the video.

- Guest User logs in and creates Cart A with a product in it
- User logs out, Cart A is forgotten, an empty Cart B is created ready for the guest user
- Guest User creates Cart B with a product in it.
- Guest User logs in, because Cart B **is not empty** the previous **is not retrieved**
- User logs out, Cart B is forgotten, an empty Cart C is created ready for the guest user
- Guest User logs in, Cart C **is empty** a previous cart **is retrieved** in this case, Cart A
- User sees Cart A

If you re-watch your video these steps should make sense. Cart merging on login is a potentially useful feature so please put your thoughts on the feature request mentioned above.

I will close this issue in favour of the FR, thanks!

**Closed as completed by nfourtythree** 2021-10-14 07:58 UTC
