### ISSUE TITLE
Custom order fields on the main order tab (and ideally choose above or below the order details)

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#865] opened 2019-05-15 00:12 UTC
### Description

With the new tab based order details view, we're currently unable to have extra fields on the main order details tab.  This means it is easy to miss thing such as order notes.

It would be great to be able to place custom fields on this tab as well - ideally being able to choose above or below the default order fields.

I think adding the Order Details tab to the order fields settings, with an un-removable Order Details on there, would be a nice way of presenting it, so that it's essentially the same as allt he rest of the field management.

At the moment I am forced into using some control panel JS to move the (essential) order notes to the main tab (if there are any):

```
// CONTROL PANEL OVERRIDES

$(document).ready(function(){

// ORDER DETAILS

    if ($("body").hasClass('commerceordersedit')) {

        // MOVE OR HIDE THE ORDER NOTES FIELD

        var notes = $.trim($('#fields-orderNotes').val());
        var $orderNotesDiv = $("#fields-orderNotes-field");

        // No notes?  hide the field..
        if (! notes){
            $orderNotesDiv.hide();
        }
        // Otherwise move it on to the main tab...
        else {
            $orderNotesDiv.detach();
            var $orderDetailsPane = $('.order-details.pane');
            $orderDetailsPane.prepend($orderNotesDiv);
        }
   }
```

**Comment by lukeholder** [comment] 2019-05-16 06:48
We will look at this once we finish the order edit screen rebuild.

**Comment by jonleverrier** [comment] 2020-02-04 10:46
I love this idea. Would you also consider setting a "default" tab perhaps?

**Comment by lukeholder** [comment] 2020-02-07 06:49
The order edit screen is being improved in 3.1 and the first tab of the custom field layout for orders should be visible on the initial screen.

**Comment by bossanova808** [comment] 2020-05-21 03:31
I've had a look at Commerce 3.1.4 and this is still an issue I think - there is no way to add fields to the main order screen still, unless I am missing something.

A really basic use case is an order notes field, or similar.  Or a fraud prevention score from a bank for operators to check things are kocher.

There really need to be some sort of mechanism to get this on the main orders page.  (Previously, I could do some JS fancy to move these fields where I wanted them but now its a Vue app, this option is no longer available I believe).

**Comment by lukeholder** [comment] 2020-12-02 07:48
This is a duplicate of https://github.com/craftcms/commerce/issues/1742

You can now add content to the bottom of the content of the order page (that would show on every tab) https://github.com/craftcms/commerce/issues/1269

**Closed by lukeholder** 2020-12-02 07:48 UTC
Labels: 💡 enhancement, 🧾 orders
