### ISSUE TITLE
Forgetting required fields on product creation puts the product in permanent Pending status

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#774] opened 2019-03-04 19:38 UTC
### Description

Tried this multiple times to make sure I'm not doing anything weird and I get consitent results with these steps:

### Steps to reproduce

1. Create a product (my product type doesn't have variants), but forget 1 or many of the required fields (sku, price, qty)
2. Save it
3. Gives you an error, so fill the missing fields and save
4. The product is now in Pending status.  You can disable it, but it's never possible to fully enable it because it always comes back in pending status.

### Additional info

- Craft version: Craft Pro 3.1.15
- Commerce version : 2.1.0.2
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21

**Comment by lukeholder** [comment] 2019-03-07 06:09
Are you getting this on the latest dev-develop? I can't reproduce this issue.

**Comment by echantigny** [comment] 2019-03-07 13:53
@lukeholder I've been able to replicate this both in the v2.1.0.2 and the dev-develop branch, without a failed attempt.

**Comment by echantigny** [comment] 2019-03-07 14:30
@lukeholder Please have a look at the entire github issue, I've made significant edits to the content of my post above.

Sorry if you always do, just wanted to make sure you see the edits.

**Comment by lukeholder** [comment] 2019-03-22 01:31
I can see the issue and will make a fix.

**Comment by ccchapman** [comment] 2019-03-25 18:37
This issue is present for me, but _not_ for the SKU field as the original issue mentions. I think having an automatic SKU format may mask the issue.

**Comment by lukeholder** [comment] 2019-03-28 07:37
@echantigny Can you confirm having the same issue with entries? I mean, if you save an entry with a missing title causing a validation error, does the entry's post date get populated any differently than products?

**Comment by echantigny** [comment] 2019-03-28 11:58
@lukeholder  No, this did not happen in normal content entries, just products.

**Comment by lukeholder** [comment] 2019-03-28 12:51
@echantigny Should be fixed on `dev-develop`, will be in the next release.

**Closed** 2019-03-28 12:50 UTC
Labels: bug, working on it
