### ISSUE TITLE
Cannot search orders with order ID

### ISSUE THREAD

**Issue by iamtompickering** [craftcms/commerce#1509] opened 2020-06-16 09:47 UTC
**Description**
When viewing orders, I can filter them down with the search by the order reference, but not the order ID. I would expect this to be possible, as it is a field that you can add to the table when viewing the order list. 

**Additional info**
- Craft version: 3.4.18
- Plugins & versions: Commerce 3.1.4

**Comment by lukeholder** [comment] 2020-06-16 09:51
Duplicate of https://github.com/craftcms/commerce/issues/1077

**Closed by lukeholder** 2020-06-16 09:51 UTC
Labels: New

**Comment by lukeholder** [comment] 2020-06-16 09:53
This will be possible when Craft implements a condition builder which will also be useful for filtering:

https://github.com/craftcms/cms/issues/1630
