### ISSUE TITLE
Managers should be able to create new orders from the CP

### ISSUE THREAD

**Issue by brandonkelly** [craftcms/commerce#41] opened 2017-03-14 20:52 UTC
- [ ] Associate them with a customer email/user account

**Comment by hendrikeng** [comment] 2018-09-19 12:06
any update if the enhancement is likely to be added soon?

**Comment by lukeholder** [comment] 2018-09-20 08:19
High on the list.

**Comment by lukeholder** [comment] 2019-03-13 18:28
Duplicate of #45

**Closed by lukeholder** 2019-03-13 18:28 UTC
Labels: enhancement
