### ISSUE TITLE
[4.x]:  Address with First Name or Last Name with more than one word get stripped

### ISSUE THREAD

**Issue by aodihis** [craftcms/commerce#3360] opened 2024-01-10 06:13 UTC
### Description
In Commerce we can specify the address with the first name and last name instead sent it as the full name, when we save it the address the data is still correct but if the cart get updated after same the address, the first/ last name with more than 1 one get stripped.

Recently also Craft has an update to add `showFirstAndLastNameFields`, so by right it should be possible to save first name or last name with more than one word.

### Steps to reproduce

1. Create an order on CMS/FE with the address first name with two words. For example: First Name: John Doe, Last Name: Eric.
2. Update the order, on cms we can just click update button or in FE can be trigger by adding coupon.

### Expected behavior
On step 2 the Name on the address should no get stripped.

### Actual behavior
The first name got stripped and become John.

### Craft CMS version

4.6.0

### Craft Commerce version

4.3.2

### Installed plugins and versions

-

**Comment by lukeholder** [comment] 2024-03-06 12:04
Duplicate of #3356

**Comment by lukeholder** [comment] 2024-03-06 12:04
Please follow the other issue for the fix. Thanks.

**Closed by lukeholder** 2024-03-06 12:04 UTC
Labels: 🐞 bug, commerce4
