### ISSUE TITLE
[4.x]: Create order : Items table doesn't respect site chosen in the order

### ISSUE THREAD

**Issue by ryssbowh** [craftcms/commerce#3065] opened 2023-01-18 16:40 UTC
### Description

I have some products enabled for a site, and some others for another site.
When I create an order in CP and choose the items, the products shown in the table are always of the same site, no matter what site I choose for the order.
Which creates wrong calculations as I have my products configured with different tax categories for the two sites.

The ajax request responsible for that is : `/index.php?p=admin_***/actions/commerce/orders/purchasables-table&site=trade&sort=&page=1&per_page=10`. The `site` parameter never changes.

### Steps to reproduce

1. Create two sites with different products for each
2. Create an order
3. Change the order site

### Expected behavior

The products for the site chosen for the order should show

### Actual behavior

The products shown are always of the same site (primary site ?)

### Craft CMS version

4.3.6.1

### Craft Commerce version

4.2.4

### PHP version

8.1

### Installed plugins and versions

-

**Comment by pdaleramirez** [comment] 2023-01-19 11:41
@ryssbowh This is not a bug. This feature is not supported yet. This is part of the multi store feature which will be released this year. You can track the progress here: https://github.com/craftcms/commerce/discussions/2283. For now products across all sites will have same values. When you create a product it will propagate to all sites.

Also we don't recommend sing Site Condition Rule on taxes. It should only factor the order's Address Information. The Site Condition Rule on Tax is not supported either. We'll improve the docs about this soon.

**Closed by pdaleramirez** 2023-01-19 11:41 UTC
Labels: 🧾 orders, 👚 products, commerce4
