### ISSUE TITLE
Coupon code in combination with shipping zone/rule crashes

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/commerce#2657] opened 2022-01-06 10:27 UTC
### Description
We're having issues with submitting the coupon code when there is a shipping rule active. Not sure if it is a bug or a misconfiguration in our PHP.

We have 2 shipping rules in our settings: 
One depending on the location and the second for free shipping above €100.
<img width="218" alt="Screenshot 2022-01-06 at 11 19 07" src="https://user-images.githubusercontent.com/42932673/148367911-712ac171-130b-405e-960f-17127911a3da.png">
<img width="769" alt="Screenshot 2022-01-06 at 11 19 31" src="https://user-images.githubusercontent.com/42932673/148367922-0455dd14-599d-40f3-a47c-fd27aa9a7e09.png">

When we fill our cart with items in total above €100 and we try to use a coupon code that will make the cart fully free (it is used for testing), the shop crashes:
```
**Error: Maximum function nesting level of '256' reached, aborting! in /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/db/Connection.php:949**
Stack trace:
#0 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/db/Connection.php(991): yii\db\Connection->quoteTableName('%commerce_shipp...')
#1 [internal function]: yii\db\Connection->yii\db\{closure}(Array)
#2 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/db/Connection.php(985): preg_replace_callback('/(\\{\\{(%?[\\w\\-\\...', Object(Closure), 'SELECT `id`, `n...')
#3 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/db/Command.php(166): yii\db\Connection->quoteSql('SELECT `id`, `n...')
#4 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/base/Component.php(181): yii\db\Command->setSql('SELECT `id`, `n...')
#5 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('sql', 'SELECT `id`, `n...')
#6 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(craft\db\Command), Array)
#7 [internal function]: yii\base\BaseObject->__construct(Array)
#8 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/di/Container.php(420): ReflectionClass->newInstanceArgs(Array)
#9 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/di/Container.php(171): yii\di\Container->build('craft\\db\\Comman...', Array, Array)
#10 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\db\\Comman...', Array, Array)
#11 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/db/Connection.php(764): yii\BaseYii::createObject(Array)
#12 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/db/Query.php(159): yii\db\Connection->createCommand('SELECT `id`, `n...', Array)
#13 /Users/hannah/Sites/aixwec/vendor/yiisoft/yii2/db/Query.php(287): yii\db\Query->createCommand(Object(craft\db\Connection))
#14 /Users/hannah/Sites/aixwec/vendor/craftcms/cms/src/db/Query.php(168): yii\db\Query->one(NULL)
#15 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/services/ShippingZones.php(81): craft\db\Query->one()
#16 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/models/ShippingRule.php(406): craft\commerce\services\ShippingZones->getShippingZoneById(NULL)
#17 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/models/ShippingRule.php(310): craft\commerce\models\ShippingRule->getShippingZone()
#18 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/base/ShippingMethod.php(127): craft\commerce\models\ShippingRule->matchOrder(Object(craft\commerce\elements\Order))
#19 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/base/ShippingMethod.php(141): craft\commerce\base\ShippingMethod->getMatchingShippingRule(Object(craft\commerce\elements\Order))
#20 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/services/ShippingMethods.php(131): craft\commerce\base\ShippingMethod->getPriceForOrder(Object(craft\commerce\elements\Order))
#21 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(2980): craft\commerce\services\ShippingMethods->getAvailableShippingMethods(Object(craft\commerce\elements\Order))
#22 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/adjusters/Shipping.php(56): craft\commerce\elements\Order->getShippingMethod()
#23 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1808): craft\commerce\adjusters\Shipping->adjust(Object(craft\commerce\elements\Order))
#24 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#25 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#26 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#27 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#28 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#29 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#30 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#31 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#32 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#33 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#34 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#35 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#36 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#37 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#38 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#39 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
#40 /Users/hannah/Sites/aixwec/vendor/craftcms/commerce/src/elements/Order.php(1830): craft\commerce\elements\Order->recalculate()
```
We noticed in the logs that this query is used a lot of times but it searches for a shipping zone with id NULL, which does not exist.
![Screenshot 2022-01-06 at 10 50 10](https://user-images.githubusercontent.com/42932673/148368268-5d8e93fa-9cda-41a9-b481-c9be9a31d131.png)

### Steps to reproduce

1. Create a shipping rule with free shipping above €100
2. Create a coupon code which makes the cart free
3. Add items in cart so the price is above €100
4. Add the coupon code

### Additional info

- Craft CMS version: 3.7.28
- Craft Commerce version: 3.3.5.1 (PRO)
- PHP version: 7.4.21
- Database driver & version: MySQL 

We don't know if this is a bug or not, but we were hoping you could help us out here! If you could not reproduce this bug we could give you admin access to our staging website.
Thanks!

**Comment by angrybrad** [comment] 2022-01-06 12:21
This is almost certainly coming from xDebug installed on that system: https://craftcms.stackexchange.com/a/1560/57https://craftcms.stackexchange.com/a/1560/57

**Comment by carolineboeykens** [comment] 2022-01-06 13:44
Thank you for your answer. This solves the error on our local setup, but on the staging and live website it still crashes. We get a php limit error:
`[06-Jan-2022 14:27:30 Europe/Brussels] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /subsites/aixwec.staging.statik.be/vendor/craftcms/commerce/src/helpers/Currency.php on line 40`

We noticed that this function is called 220 times in one request. Could this have something to do with it?
**craft\commerce\elements\Order->recalculate()**

**Comment by janhenckens** [comment] 2022-01-07 10:41
Hey Brad

We dug a little bit further on this and it seems to be a happening only when these conditions are met:
- the matched shipping rule "Order total value" is set to "Value of products with applied discounts."
- the coupon takes the cart total to an amount below the minimum set in the shipping rule.

We have tested with these case:

- Cart total is €170, Free shipping above €100, Coupon takes of 100%
**=> recalculating the cart crashes**

- Cart total is €170, Free shipping above €100, Coupon takes of 50%
**=> recalculating the cart crashes**

- Cart total is €170, Free shipping above €100, Coupon takes of 20%
**=> recalculating the cart works**

- Cart total is €280, Free shipping above €100, Coupon takes of 60%
**=> recalculating the cart works**

Setting the shipping rule to "Value of products before any discounts are applied." removes the issue, regardless of what prices, discounts and totals you and up with.

What seems to be happening is:
- shipping is calculate and the "free shipping" rule is applied
- coupon is added, which recalculates the cart and takes the total below the threshold of the shipping rule.
- shipping rule is calculated again because it is set to "Value of products with applied discounts"

And there we see an endless loop of running ->recalculate() until we hit the servers execution timeout.

Happy to share the code & database if that helps!

**Comment by nfourtythree** [comment] 2022-01-07 14:22
Hi @janhenckens 

Thank you for the extra details.

I have just tried this with the latest version of Craft and Commerce while also using the example templates.

Unfortunately, I was unable to replicate the issue.

This was my shipping rule setting:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/geudrGNQ/1aab3ee9-5070-41a0-95a9-58c9364020be.png?v=fc1d6ac28799f0810eb5c1b556872af2)

This was my discount setting:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/NQuxv0Q9/33b215b4-d459-4138-a108-878ef89af21d.png?v=e3458b8246bbc4318d6794e4704a516b)

And here was the resulting cart once I had the correct total value, added the coupon code and selected the shipping method:

![](https://p191.p3.n0.cdn.getcloudapp.com/items/04uLgjwX/ce88a951-544e-4e73-be19-36e0e88bc6cf.jpg?v=8a7e004f89117c0a6f685a431c4c03c3)

Are you able to replicate the issue with a fresh install and the example templates? Doing this would also then isolate any other potential issues may that be other plugins or custom module code.

Thanks!

**Comment by janhenckens** [comment] 2022-01-10 11:49
Hey @nfourtythree. I did some more testing on a fresh install and couldn't reproduce it there either.
Then I made sure we really were on the latest version, **which we weren't** .
Tried to reproduce after updating and it seems to be fixed now.

**Comment by nfourtythree** [comment] 2022-01-10 12:48
Hi @janhenckens 

Thank you for your message and good to know that this is all sorted now.

Thanks!

**Closed by nfourtythree** 2022-01-10 12:48 UTC
Labels: ℹ️ status: need more info
