### ISSUE TITLE
Error on adding new field when Commerce is not enabled

### ISSUE THREAD

**Issue by janhenckens** [craftcms/commerce#675] opened 2019-01-31 14:42 UTC
### Description
I installed `craftcms/commerce` through composer (just that, didn't install it in the site yet) and went to add a new field. The results in the following error:

```
yii\base\InvalidConfigException: Unable to locate message source for category 'commerce'. in /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/i18n/I18N.php:201
Stack trace:
#0 /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/i18n/I18N.php(89): yii\i18n\I18N->getMessageSource('commerce')
#1 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/i18n/I18N.php(327): yii\i18n\I18N->translate('commerce', 'Product', Array, 'en-GB')
#2 /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/BaseYii.php(526): craft\i18n\I18N->translate('commerce', 'Product', Array, 'en-GB')
#3 /Users/jhenckens/Sites/woosho/vendor/craftcms/commerce/src/elements/Product.php(180): yii\BaseYii::t('commerce', 'Product')
#4 /Users/jhenckens/Sites/woosho/vendor/statikbe/craft-cta-field/src/models/ElementLinkType.php(56): craft\commerce\elements\Product::displayName()
#5 /Users/jhenckens/Sites/woosho/vendor/statikbe/craft-cta-field/src/fields/CTAField.php(300): statikbe\cta\models\ElementLinkType->getDisplayName()
#6 /Users/jhenckens/Sites/woosho/vendor/verbb/super-table/src/services/SuperTableMatrixService.php(231): statikbe\cta\fields\CTAField->getSettingsHtml()
#7 /Users/jhenckens/Sites/woosho/vendor/verbb/super-table/src/services/SuperTableMatrixService.php(45): verbb\supertable\services\SuperTableMatrixService->_getFieldOptionsForConfigurator()
#8 /Users/jhenckens/Sites/woosho/vendor/verbb/super-table/src/fields/SuperTableField.php(852): verbb\supertable\services\SuperTableMatrixService->getMatrixSettingsHtml(Object(craft\fields\Matrix))
#9 /Users/jhenckens/Sites/woosho/vendor/verbb/super-table/src/fields/SuperTableField.php(286): verbb\supertable\fields\SuperTableField->_getFieldOptionsForConfigurator()
#10 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/fields/Matrix.php(818): verbb\supertable\fields\SuperTableField->getSettingsHtml()
#11 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/fields/Matrix.php(278): craft\fields\Matrix->_getFieldOptionsForConfigurator()
#12 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Extension/Core.php(1626): craft\fields\Matrix->getSettingsHtml()
#13 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/helpers/Template.php(73): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method', false, false)
#14 /Users/jhenckens/Sites/woosho/storage/runtime/compiled_templates/12/12fe6e942174ceedf764badaca68be3d0d71a704dba251617398dd894add3359.php(253): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig_Source), Object(craft\fields\Matrix), 'getSettingsHtml', Array, 'method')
#15 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_51f5f4ef860a4c9bc85a7167cf79b4904359fc057fd87c303b1cc7708dd23dfa->block_content(Array, Array)
#16 /Users/jhenckens/Sites/woosho/storage/runtime/compiled_templates/84/84ebbe1128438cd9bd916860bb0b7f4405af86ae8d2146a932293723eb906de4.php(648): Twig_Template->displayBlock('content', Array, Array)
#17 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_435c83751e4b36ca4adf8d5a294acf30602cc37948dfb4c21996fad1fd2c0e0d->block_main(Array, Array)
#18 /Users/jhenckens/Sites/woosho/storage/runtime/compiled_templates/84/84ebbe1128438cd9bd916860bb0b7f4405af86ae8d2146a932293723eb906de4.php(533): Twig_Template->displayBlock('main', Array, Array)
#19 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(189): __TwigTemplate_435c83751e4b36ca4adf8d5a294acf30602cc37948dfb4c21996fad1fd2c0e0d->block_body(Array, Array)
#20 /Users/jhenckens/Sites/woosho/storage/runtime/compiled_templates/bb/bbdebb8a64862c6f577728e7e8e5e50436bbde6e9f3e9a3cae5834ae3d90324d.php(60): Twig_Template->displayBlock('body', Array, Array)
#21 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_26569bd9a7adb66e0848165e09769f95d8d04263cb17a6075312777eaa21d8ad->doDisplay(Array, Array)
#22 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#23 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#24 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#25 /Users/jhenckens/Sites/woosho/storage/runtime/compiled_templates/db/dba1701744975821caaeb06afdc13e824b006373d6abb856de9a60e68635d2db.php(40): craft\web\twig\Template->display(Array, Array)
#26 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_078d98e0b656d239215c1e07097545eb771d5883c5bce9ca2ec3431e816e5294->doDisplay(Array, Array)
#27 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#28 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#29 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#30 /Users/jhenckens/Sites/woosho/storage/runtime/compiled_templates/84/84ebbe1128438cd9bd916860bb0b7f4405af86ae8d2146a932293723eb906de4.php(95): craft\web\twig\Template->display(Array, Array)
#31 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_435c83751e4b36ca4adf8d5a294acf30602cc37948dfb4c21996fad1fd2c0e0d->doDisplay(Array, Array)
#32 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#33 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#34 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#35 /Users/jhenckens/Sites/woosho/storage/runtime/compiled_templates/12/12fe6e942174ceedf764badaca68be3d0d71a704dba251617398dd894add3359.php(95): craft\web\twig\Template->display(Array, Array)
#36 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(386): __TwigTemplate_51f5f4ef860a4c9bc85a7167cf79b4904359fc057fd87c303b1cc7708dd23dfa->doDisplay(Array, Array)
#37 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(49): Twig_Template->displayWithErrorHandling(Array, Array)
#38 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(363): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#39 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/twig/Template.php(31): Twig_Template->display(Array, Array)
#40 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Template.php(371): craft\web\twig\Template->display(Array)
#41 /Users/jhenckens/Sites/woosho/vendor/twig/twig/lib/Twig/Environment.php(289): Twig_Template->render(Array)
#42 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/View.php(337): Twig_Environment->render('settings/fields...', Array)
#43 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/View.php(384): craft\web\View->renderTemplate('settings/fields...', Array)
#44 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('settings/fields...', Array)
#45 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/controllers/FieldsController.php(243): craft\web\Controller->renderTemplate('settings/fields...', Array)
#46 [internal function]: craft\controllers\FieldsController->actionEditField(NULL, Object(craft\fields\PlainText), '1')
#47 /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#48 /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#49 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-field', Array)
#50 /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-field', Array)
#51 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('fields/edit-fie...', Array)
#52 /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('fields/edit-fie...', Array)
#53 /Users/jhenckens/Sites/woosho/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#54 /Users/jhenckens/Sites/woosho/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#55 /Users/jhenckens/Sites/woosho/public/index.php(21): yii\base\Application->run()
#56 {main}

```

The error doesn't occur when Commerce is installed & active.

### Steps to reproduce

1. Install craftcms/commerce through composer
2. Add a new field

### Additional info

- Craft version: 3.16.1
- PHP version: 7.2.10
- Database driver & version: 5.7
- Plugins & versions: Commerce 2.0.2

**Comment by lukeholder** [comment] 2019-02-01 16:53
Hi, I can't reproduce this issue. Can you reproduce it again?

**Comment by lukeholder** [comment] 2019-02-18 12:08
Please let me know, closing until then.

**Closed by lukeholder** 2019-02-18 12:08 UTC
Labels: need more info
