### ISSUE TITLE
Unable to save product when expired

### ISSUE THREAD

**Issue by tim-pixeldeluxe** [craftcms/commerce#737] opened 2019-02-21 08:46 UTC
### Description
Whenever I try to save an expired product I get an invalid product ID error.
```
yii\base\InvalidConfigException: Invalid product ID: 1063 in /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/elements/Variant.php:314
Stack trace:
#0 /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/elements/Variant.php(874): craft\commerce\elements\Variant->getProduct()
#1 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/Model.php(350): craft\commerce\elements\Variant->beforeValidate()
#2 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/services/Elements.php(429): yii\base\Model->validate()
#3 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/services/Elements.php(1553): craft\services\Elements->saveElement(Object(craft\commerce\elements\Variant), true, false)
#4 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/services/Elements.php(525): craft\services\Elements->_propagateElement(Object(craft\commerce\elements\Variant), false, Array)
#5 /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/elements/Product.php(720): craft\services\Elements->saveElement(Object(craft\commerce\elements\Variant), false)
#6 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/services/Elements.php(515): craft\commerce\elements\Product->afterSave(false)
#7 /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/controllers/ProductsController.php(221): craft\services\Elements->saveElement(Object(craft\commerce\elements\Product))
#8 [internal function]: craft\commerce\controllers\ProductsController->actionSaveProduct()
#9 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-product', Array)
#12 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-product', Array)
#13 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('commerce/produc...', Array)
#14 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('commerce/produc...', Array)
#15 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Applications/MAMP/htdocs/projectname/public_html/index.php(21): yii\base\Application->run()
#18 {main}
```

I'm also unable to delete them because of the same error.
```
yii\base\InvalidConfigException: Invalid product ID: 1548 in /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/elements/Variant.php:314
Stack trace:
#0 /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/elements/Variant.php(288): craft\commerce\elements\Variant->getProduct()
#1 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/base/Element.php(2078): craft\commerce\elements\Variant->getFieldLayout()
#2 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/base/Element.php(1899): craft\base\Element->fieldLayoutFields()
#3 /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/elements/Variant.php(894): craft\base\Element->beforeDelete()
#4 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/services/Elements.php(957): craft\commerce\elements\Variant->beforeDelete()
#5 /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/elements/Product.php(766): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Variant))
#6 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/services/Elements.php(1000): craft\commerce\elements\Product->afterDelete()
#7 /Applications/MAMP/htdocs/projectname/vendor/craftcms/commerce/src/controllers/ProductsController.php(175): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Product))
#8 [internal function]: craft\commerce\controllers\ProductsController->actionDeleteProduct()
#9 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('delete-product', Array)
#12 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-product', Array)
#13 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('commerce/produc...', Array)
#14 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('commerce/produc...', Array)
#15 /Applications/MAMP/htdocs/projectname/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /Applications/MAMP/htdocs/projectname/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Applications/MAMP/htdocs/projectname/public_html/index.php(21): yii\base\Application->run()
#18 {main}
```

### Steps to reproduce

1. Have an expired product
2. Then try to save/delete it

### Additional info

- Craft version: 3.1.8
- PHP version: 7.1.6
- Database driver & version: MySQL 5.5.59
- Plugins & versions: Craft Commerce 2.0.4

**Comment by lukeholder** [comment] 2019-02-25 19:24
Root cause is duplicate of #683

**Closed by lukeholder** 2019-02-25 19:24 UTC
