### ISSUE TITLE
Total Price and Paid Amount in Orders returns 0

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#1294] opened 2020-02-21 16:21 UTC
### Description

For existing orders and orders created manually, the Total Price and Paid Amount values always seem to return 0.

![Screen Shot 2020-02-21 at 17 13 38](https://user-images.githubusercontent.com/2373940/75051209-bcc0c400-54cd-11ea-8572-7ef569b06b41.png)

### Steps to reproduce

1. Go to an existing order
2. Check the Total Price and Paid Amount values

or

1. Create a new order
2. Add a line item
3. Assign order to customer
4. Notice how the total is still 0
5. Make a manual payment
6. Notice how the Paid Amount value returns 0

### Additional info

- Craft version: 3.4.7.2
- PHP version: 7.3.13
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.0.10

**Comment by samhibberd** [comment] 2020-02-21 18:07
See #1293

**Comment by nfourtythree** [comment] 2020-02-21 18:13
Duplicate of #1293

**Closed by nfourtythree** 2020-02-21 18:13 UTC
