### ISSUE TITLE
New "Shipping Category Conditions" doesn’t work as expected on older products

### ISSUE THREAD

**Issue by jesuismaxime** [craftcms/commerce#688] opened 2019-02-06 16:41 UTC
### Description
   
I have 2 Shipping Categories : *General* and *None*.
I create a "No shipping" shipping method and set the conditions properly under the Conditions tab :
- *General* to Disallow
- *None* to Require

On the Shipping page of the checkout process, I always got the "No Shipping" option on both case:
Case 1 : Only one *General* product in cart  
Case 2 : Only one *None* product in cart

Case 2 is obviously legit, but Case 1 is not expected.

Note: If I disallow both *General* and *None*, in both case the No Shipping method is not listed - and I triple check, my *General* shipping category product types are well set. 

**Important : None of the above happens to a product that match the *General* shipping category created after the conditions was created. (Caches cleared)**

### Additional info

- Craft version: 3.1.7
- PHP version: 7.2.10
- Database driver & version: MySQL 5.7.23
- Plugins & versions: Commerce 2.0.4

**Comment by jesuismaxime** [comment] 2019-02-06 16:50
I save the problematic product again (change its name/handle/stock) and everything work normally now, but there's definitely something wrong here.

**Comment by lukeholder** [comment] 2019-02-13 06:09
Hi @jesuismaxime 

This is my attempt to reproduce: https://jmp.sh/ugwv1tr

As you can see I can't reproduce with the example templates. And the config as you have described.

Let me know if I have done something wrong when I was trying to reproduce.

**Comment by xhuang9** [comment] 2019-03-08 04:17
I have a similiar error on the exact same version as @jesuismaxime.

**Comment by lukeholder** [comment] 2019-03-13 20:00
Looks like we should automatically resave all products of any product type that was changed within a category save.

**Comment by jesuismaxime** [comment] 2019-03-13 20:32
Maybe add this as an action to perform (mostly if the Commerce contains thousands of products) through the Shipping Category Conditions.

**Comment by xhuang9** [comment] 2019-03-22 06:07
@lukeholder 
I had another use case for the "re-save commerce product button".

I had categories that named "Xxx & Xxx" Slug is "xxx-xxx"
Now I change it to "Yyy & Yyy" Slug is "yyy-yyy"

That category is a field in product called: "Categories"

Now If I ran element search query:
craft.products.search("Categories::yyy-yyy")
The products won't show up.

If I ran element search query:
craft.products.search("Categories::xxx-xxx")
The products show up.

Then I go re-save all the product has that category.
It then updated and show up in the first query.

**Comment by steve-eaccent** [comment] 2019-06-03 05:11
We've also had this issue, and it looks like manually resaving our products in the CraftCMS admin panel updates shipping categories.

**Comment by lukeholder** [comment] 2019-07-03 09:37
Thanks all, this will be fixed in the next major release of Commerce.

**Comment by lukeholder** [comment] 2019-08-29 07:18
Thanks for reporting everyone, this is fixed for the next release. Product affected by a change to the category<->product type relationship will be resaved and receive the first category available to them by default.

**Closed** 2019-08-29 07:17 UTC
Labels: bug, status: need more info
