### ISSUE TITLE
Get product lineItem for the last item added to the cart

### ISSUE THREAD

**Issue by mdunbavan** [craftcms/commerce#488] opened 2018-09-14 15:59 UTC
### Description

So we have a catalogue page where users can add many items to the cart if they want. They select a size from the dropdown and add to cart in which a dropdown from the ajax success would get that added items title inside the dropdown with its associated price and sku.

This enables users to see what was added from the last add to cart and for me as the developer to target the correct item.

Currently there is no easy way unless I am missing something completely here.

### Additional info

- Craft version: 3
- PHP version: 7.1
- Database driver & version: mysql latest
- Plugins & versions: craft commerce 2

**Comment by lukeholder** [comment] 2018-09-18 14:30
Hi @mdunbavan not sure what you are trying to achieve sorry. Could you try to clarify.

**Comment by lukeholder** [comment] 2019-09-24 21:39
Duplicate of https://github.com/craftcms/commerce/issues/929

**Closed by lukeholder** 2019-09-24 21:39 UTC
Labels: enhancement
