### ISSUE TITLE
Ignore sales when this discount is applied effects carts without the discount applied

### ISSUE THREAD

**Issue by Tam** [craftcms/commerce#1206] opened 2020-01-07 11:39 UTC
### Description
If I have a discount that has the `Ignore sales when this discount is applied.` enabled it will cause sales to be ignored regardless of whether or not the discount has been applied to the cart.

### Steps to reproduce

1. Create a sale
2. Create a discount with `Ignore sales when this discount is applied.` enabled
3. Add a product to your cart that is targeted by the sale
4. Note that the price in the cart is now the original price, not the sale price.

### Additional info

- Craft version: Craft Pro 3.3.19
- PHP version: 7.3.9
- Database driver & version: PostgreSQL 11.5
- Plugins & versions:

Plugin | Version
:-- | :--
Craft Commerce | 2.2.13

**Comment by lukeholder** [comment] 2020-01-23 21:24
Can you please send your DB dump/backup to support@craftcms.com so we can try to reproduce? Thanks.

**Comment by Coalescent** [comment] 2020-01-23 21:38
I've run into this behaviour as well (as documented here: https://craftcms.stackexchange.com/questions/33455/commerce-2-sales-not-present-in-cart-lineitems). I can send a db backup as well if needed.

**Comment by lukeholder** [comment] 2020-01-23 21:46
Please send a DB backup/dump, thanks.

**Comment by JustJarethB** [comment] 2020-01-24 10:25
I also have this issue as documented here, I did not fully realise the cause before. The bug sprouted somewhere between `2.2.9 => 2.2.11`
https://github.com/craftcms/commerce/issues/1229

**Comment by Tam** [comment] 2020-01-24 13:30
Sorry, I should have mentioned that this is re-creatable on a fresh install of Commerce (just tested using 2.2.14).

**Comment by lukeholder** [comment] 2020-01-24 18:25
@Tam @JustJarethB @Coalescent Please can someone send a DB dump or backup so we can try to reproduce this issue and debug. Thanks.

**Comment by Coalescent** [comment] 2020-01-24 18:57
I sent one last night to support and got a response from @angrybrad, so I assume someone on your end has it?

**Comment by angrybrad** [comment] 2020-01-24 19:13
@Coalescent yup got it and assigned it to @lukeholder @nfourtythree

**Comment by lukeholder** [comment] 2020-01-24 23:24
Thanks for reporting. This has been fixed for the next release due out very soon.

**Closed** 2020-01-24 23:23 UTC
Labels: 🐞bug, 🔎status: investigating

**Comment by lukeholder** [comment] 2020-01-26 00:56
This is now fixed in Commerce 2.2.15
