### ISSUE TITLE
Enhancement - Allow shipping to be calculated based off total after discounts

### ISSUE THREAD

**Issue by davist11** [craftcms/commerce#875] opened 2019-05-21 15:15 UTC
### Description

We have a situation where we want the shipping to apply after the discount. Currently, shipping is being calculated based of the total cost of items, before discounts.

Ideally, there would be a setting allowing shipping to be calculated based off the order subtotal after discounts, rather than the total order price before discounts. So a user would see the total cost of their items (say $1000), their discount (say -$100). The subtotal would then be $900 and shipping would be calculated based on that $900 subtotal.

This was referenced in a <a href="https://craftcms.stackexchange.com/questions/26613/craft-commerce-shipping-total-order-price-rule">StackExchange thread</a> last year.

### Additional info

- Craft version: Craft Pro 3.1.24
- Commerce version: 2.1.4

**Comment by davist11** [comment] 2019-05-24 14:55
Just wanted to bump this to get any sort of potential timeline. If not, then we will likely need to write our own shipping adjuster.

**Comment by sjelfull** [comment] 2019-05-27 12:09
@davist11 Could you modify the default order of the adjusters?

**Comment by lukeholder** [comment] 2019-05-27 15:57
The issue here is that discounts can also affect shipping costs. It might be best to write you own shipping adjuster for now. Keeping the ticket open though, as we should look to improve the shipping conditions soon.

**Comment by lukeholder** [comment] 2019-10-11 02:36
We can look to add logic to the shipping adjuster to run all discounts and determine the possible prices of the line items after discount and use those prices in determining shipping rules.

**Comment by iamtompickering** [comment] 2020-12-18 08:53
#1800

**Comment by iamtompickering** [comment] 2020-12-18 08:54
Having the same issue here #1800

**Comment by iamtompickering** [comment] 2020-12-18 09:08
Just to add to this, I have been trying to resolve this by adjusting the following lines in `src/models/ShippingRule.php`

```
        if ($this->minTotal && $this->minTotal > $order->getItemSubtotal() ) {
            return false;
        }
        if ($this->maxTotal && $this->maxTotal <= $order->getItemSubtotal() ) {
            return false;
        }
```

to 

```
        if ($this->minTotal && $this->minTotal > $order->getTotalPrice() ) {
            return false;
        }
        if ($this->maxTotal && $this->maxTotal <= $order->getTotalPrice() ) {
            return false;
        }
```

This seems to update the price of the shipping method when outputting it via `availableShippingMethods`, but the order totals do not get updated. Is there anything that would need to be adjusted to make the above change update the totals accordingly?

**Comment by lukeholder** [comment] 2021-01-11 11:55
Duplicate of https://github.com/craftcms/commerce/issues/875

**Closed by lukeholder** 2021-01-11 11:55 UTC
Labels: 💡 enhancement, 📬 shipping

**Comment by sjelfull** [comment] 2021-01-11 12:31
@lukeholder I think you just marked this a duplicate of itself?
