### ISSUE TITLE
Shipping method exclude or include multiple zones

### ISSUE THREAD

**Issue by mrksmts** [craftcms/commerce#443] opened 2018-08-14 08:50 UTC
### Description
We have a few different shipping zones:
- Netherlands
- Europe (complete Europe except for Netherlands)
- Worldwide (rest of the world excluding Netherlands and Europe)

To create worldwide we had to add all the countries that were not in the other two zones manually.

### Suggestion
Ability to exclude zones when making a Shipping method rule.

### Examples
- Everywhere, but exclude the zones Europe and Netherlands
- Instead of creating a zone that does not include country X; Include zone Europe and exclude zone Netherlands

**Comment by j-greig** [comment] 2019-07-16 13:56
+1 for this request, thanks :)

**Comment by lukeholder** [comment] 2019-10-10 23:31
Duplicate of #200

**Closed by lukeholder** 2019-10-10 23:31 UTC
Labels: ➕enhancement, 📬 shipping
