### ISSUE TITLE
3.0-RC1 Twig Syntax Error in Customers section in the CP

### ISSUE THREAD

**Issue by jonleverrier** [craftcms/commerce#1218] opened 2020-01-16 09:25 UTC
### Description

In the CP, in the customers section, when you click into a customer it returns a Twig Syntax Error in `craft/vendor/craftcms/commerce/src/templates/customers/_includes/_customerTables.html`;

```
The "defined" test only works with simple variables.
```

```
[ Line 71 ] title: order.reference|e ?? order.shortNumber|e,
```

### Steps to reproduce

1. Go to the customers section
2. Click into a customer by clicking on the `email` or `user` link
3. Page returns a Twig Syntax Error

### Additional info

- Craft version: 3.4.0-RC1.1
- PHP version: 7.3
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Commerce 3.0.0-RC1

**Comment by nfourtythree** [comment] 2020-01-16 11:14
Hi @jonleverrier 

Thanks for bringing this up, this is actually a duplicate of https://github.com/craftcms/commerce/issues/1216

Closing this issue

**Closed by nfourtythree** 2020-01-16 11:14 UTC
