### ISSUE TITLE
Ability to void transactions

### ISSUE THREAD

**Issue by Mosnar** [craftcms/commerce#1574] opened 2020-07-16 21:16 UTC
**What are you trying to do?**
Before a captured payment has settled, some (all?) gateways will reject processing refund transactions. During this period, an alternative is creating a `void` on the entire transaction (partial voids are not possible as far as I know). Commerce doesn't currently have a concept of a payment gateway's status regarding a transaction - only that it was successful or not. Ideally, a Commerce Gateway should have the ability to tell the control panel that a transaction can be voided rather than refunded - once a void is created, there needs to be a way of showing the transition of that transaction into a successful void.

**Comment by lukeholder** [comment] 2020-07-17 08:25
Duplicate of https://github.com/craftcms/commerce/issues/611

**Closed by lukeholder** 2020-07-17 08:25 UTC
Labels: New, 💡 enhancement
