### ISSUE TITLE
[4.x]: Order `hasMatchingAddresses` ignore fullName

### ISSUE THREAD

**Issue by billmn** [craftcms/commerce#2955] opened 2022-08-31 11:19 UTC
### Description
I have two addresses that are the identical but have different "Full Name" values.
The `hasMatchingAddresses` method returns `true` instead of `false`.

### Steps to reproduce

1. Add `fullName` native field in Address Field's layout
2. Create two identical adresses but for one insert a different "Full Name"
3. Use `hasMatchingAddresses` method to compare this two addresses

### Expected behavior
If the full name is different, `hasMatchingAddresses` should return `false`.

### Actual behavior
Even if the full name is different, `hasMatchingAddresses` return `true`.

### Craft CMS version

4.2.3

### Craft Commerce version

4.1.0

### PHP version

8.0.21

### Operating system and version

macOS 12.5.1

### Database type and version

MariaDB 15.1

### Installed plugins and versions

-

**Comment by nfourtythree** [comment] 2022-08-31 11:23
Hi @billmn 

This is a duplicate of #2917

Please follow along there and any any extra info on that issue (if required).

Thanks!

**Closed by nfourtythree** 2022-08-31 11:23 UTC
Labels: 🐞 bug, commerce4
