### ISSUE TITLE
Use same address for billing with custom address validation rules

### ISSUE THREAD

**Issue by Wiejeben** [craftcms/commerce#702] opened 2019-02-09 23:04 UTC
### Description
When placing an order with a logged in account and checking the "use same address for billing" checkbox, I get form validation errors from the billing fields (shipping fields are complying to the validation rules).

Note: Guest accounts are not effected by this bug.

### Steps to reproduce
1. Apply custom validation rules like this:
```php
Event::on(
    Address::class,
    Address::EVENT_REGISTER_ADDRESS_VALIDATION_RULES,
    function (RegisterAddressRulesEvent $event) {
        $event->rules[] = [['address1', 'city', 'zipCode', 'phone'], 'required'];
    }
);
```

2. Make sure you are logged in (with an account that has placed an orders before, I haven't done tests with a brand new account yet)

3. Create an order with the shipping address fields filled so that complies with the validation.

4. Make sure you have "Use same address for billing" 

5. You should now get form validation errors for the billing fields.

### Additional info

- Craft version:  3.1.8
- PHP version: 7.3.0
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Craft Commerce 2.0.4

**Comment by lukeholder** [comment] 2019-02-11 09:07
Hi, I cant reproduce validation errors on the billing address. I have made a short screencast trying to reproduce with the example templates: https://jmp.sh/xdHTveG

Let me know if you can nail down how to trigger it with the example templates. Can you also confirm you are not using old addresses that previously did not meet the new valiation rules you added.

**Comment by Wiejeben** [comment] 2019-02-11 18:58
I'm not entirely sure why you can't reproduce the bug. You might have to place an order without the additional validation.

Here is a video of me placing an order in a clean install of Craft: https://youtu.be/G6yD576x_IA

**Comment by Wiejeben** [comment] 2019-02-20 10:04
@lukeholder Is this enough for you to be able to reproduce this?

**Comment by nfourtythree** [comment] 2019-08-29 15:33
Hi @Wiejeben 

Spent quite a bit of time trying to replicate this but I was unable to reproduce as described.

The only way was to put in the validation after a successful order, this would then give a validation error on the next trip through the checkout. But that is expected behaviour as the stored address wasn't valid according to the new rules.

I am going to close this for now but will re-open if we can find reliable way to replicate the issue.

Thanks.

**Closed by nfourtythree** 2019-08-29 15:33 UTC
Labels: status: investigating, status: need more info
