### ISSUE TITLE
Per Email Address Discount Limit - error if user not logged in

### ISSUE THREAD

**Issue by paddling** [craftcms/commerce#1475] opened 2020-05-27 15:41 UTC
**Description**
When creating a discount that has a `Per Email Address Discount Limit` an error is thrown IF the user is not already logged in (for example in an incognito window)

**To Reproduce**
1. In the CP, create a discount that uses a coupon code:
    ![image](https://user-images.githubusercontent.com/58182286/83040905-d2ceab00-a00d-11ea-883d-aaab12ddf4f1.png)
2. Set the `Per Email Address Discount Limit` to be 1 (or any other non-zero number)
![image](https://user-images.githubusercontent.com/58182286/83041009-fb56a500-a00d-11ea-941d-83752ffc2272.png)
1. In an incognito window, add an item to the cart and apply the discount on the front-end.  Site will generate error.
![image](https://user-images.githubusercontent.com/58182286/83041588-a23b4100-a00e-11ea-8ee7-04dd51b9fea9.png)

1. However, as soon as the user has provided an email address (either by logging in or proceeding as a guest) the coupon works as expected.  Null state email generates error.

**Expected behavior**
Coupon should work regardless of whether email has been provided (and then verified further in the checkout) OR user should be prompted to log in in order to use coupon.

**Additional info**
- Craft version: 3.4.18
- Commerce version: 3.1.3

**Comment by nfourtythree** [comment] 2020-05-28 06:56
Hi @paddling 

This is a duplicate of #1455 will close this issue, please follow the previous issue for updates.

Thanks.

**Closed by nfourtythree** 2020-05-28 06:56 UTC
Labels: New
