### ISSUE TITLE
Promo price field per product/variant

### ISSUE THREAD

**Issue by alexanderloewe** [craftcms/commerce#2206] opened 2021-06-15 09:56 UTC
**What are you trying to do?**
It would be very nice to have the option to discount a product or a variant by hand with a sale / promo price field.
In this way you don't have to use the sales or discount feature for one special discount.

It would be great to have a checkbox in the product type settings to enable this option, because I don't think that this option is relevant for everyone.

**What's your proposed solution?**
- It also makes it much easier for users which don't have that much experience by calculating discounts.
- We think this is a very basic function for a commerce platform. Most commerce software has something like this.
- Two of our clients have requested something like this.

**Additional context**

<img width="567" alt="Bildschirmfoto 2021-06-07 um 16 35 48" src="https://user-images.githubusercontent.com/69263307/122031591-235aa700-cdcf-11eb-8f92-8c82c8ab8a71.png">

**Comment by nfourtythree** [comment] 2021-06-21 08:28
Hi @alexanderloewe 

This is a duplicate of #193

Please follow along with that feature request and provide any feedback/thoughts there.

Thanks!

**Closed by nfourtythree** 2021-06-21 08:28 UTC
Labels: 👚 products, 💡 enhancement, 📣 promotions
