### ISSUE TITLE
Send specific payment source to subscription

### ISSUE THREAD

**Issue by millman2394** [craftcms/commerce#1686] opened 2020-08-28 14:24 UTC
**What are you trying to do?**
There doesn't seem to be a way to use a specific card when signing up for a subscription. it will automatically choose the last entered card the user has. I need a way of sending one of the `craft.commerce.paymentSources.getAllPaymentSourcesByUserId` to the subscribe action on the controller. The controller accepts the planUid, but I don't see anything about a payment source id.

This is very frustrating

I think based on these lines in the controller:

```
$paymentForm = $gateway->getPaymentFormModel();
                $paymentForm->setAttributes($request->getBodyParams(), false);

                if ($paymentForm->validate()) {
                    $plugin->getPaymentSources()->createPaymentSource(Craft::$app->getUser()->getId(), $gateway, $paymentForm);
                }
```

(and the Javascript commerce has as one of their examples in the templates)

```
// Tokenize the credit card details and create a payment source
            this.stripeInstance.createPaymentMethod('card', card, paymentData).then(function(result) {
                if (result.error) {
                    this.displayMessage(result.error.message);
                    $form.data('processing', false);
                } else {
                    // Add the payment source token to the form.
                    $form.append($('<input type="hidden" name="paymentMethodId"/>').val(result.paymentMethod.id));
                    $form.get(0).submit();
                }
            }.bind(this));
        }.bind(this));
```

They're appending `$form.append($('<input type="hidden" name="paymentMethodId"/>').val(result.paymentMethod.id));` and I think whenever `paymentMethodId` is sent to the controller, it will automatically try to create a new payment source.

I can't find how to just send an existing payment source to this action and have it charge that card.

**Comment by lukeholder** [comment] 2020-09-17 08:46
Duplicate of https://github.com/craftcms/commerce/issues/1686

**Closed by lukeholder** 2020-09-17 08:46 UTC
Labels: New, 💡 enhancement

**Comment by millman2394** [comment] 2020-09-23 14:46
> Duplicate of #1686

this IS #1686? What do you mean duplicate?

**Comment by lukeholder** [comment] 2020-09-29 05:00
#1185 is there this can be tracked sorry
