### ISSUE TITLE
Updating cart should not validate addresses

### ISSUE THREAD

**Issue by Mosnar** [craftcms/commerce#2199] opened 2021-06-13 18:36 UTC
**Description**

If for some reason a customer has an address validation issue, they will be unable to update their cart (e.g. add/remove items) until this validation issue is fixed. This can be problematic, especially if address validation is added as a feature after launching ecommerce and suddenly customers with new validation issues are unable to add items to their cart.

I brought this up here as well: https://github.com/craftcms/commerce/issues/1941#issuecomment-853359724

**To Reproduce**
1. Add an address to a cart
2. Add validation rules to the address model that makes the address added in Step 1 invalid
3. Attempt to add an item to the cart and see that it fails

**Expected behavior**
The cart should be able to be modified independently of the address. Addresses should only be revalidated when explicitly updated or on payment.

**Additional info**
- Craft version: 3.5.19.1
- Commerce version: 3.2.17.3
- PHP version: 7.4.x

**Additional context**

Related issue: #1941 
Related docs: https://craftcms.com/docs/commerce/3.x/addresses.html#validating-addresses
Related StackExchange: https://craftcms.stackexchange.com/questions/15897/craft-commerce-validation-on-address-fields

**Comment by pdaleramirez** [comment] 2021-06-17 09:20
@Mosnar Closing this issue cause it's a duplicate of #1941, I've also commented a workaround for this.

**Closed by pdaleramirez** 2021-06-17 09:20 UTC
Labels: 🏠 addresses
