### ISSUE TITLE
[4.x]: Sales are not applied to variants, works only when all purchasables and all categories are activated

### ISSUE THREAD

**Issue by stefanfriedrich** [craftcms/commerce#3097] opened 2023-02-24 16:47 UTC
### Description

I want to add a sale to certain variants, not to all. This doesn't work.
There are no other discounts/sales active. All products are promotable.
If I chose "all purchasables" and "all categories" - and only then - it works as expected.
I have no categories so far.
If I chose all purchasables by hand - also doesn't work.

### Steps to reproduce

1. Create a product with variants
2. Creat a sale
3. Chose a variant for the sale
4. variant.onSale will be false

### Expected behavior

variant.onSale should be true

### Actual behavior

variant.onSale should is false

### Craft CMS version

 4.3.10

### Craft Commerce version

4.2.5.1

### Installed plugins and versions

- CP Field Inspect 1.4.4
- Craft Commerce 4.2.5.1
- Dumper 3.0.1
- Feed Me 5.0.5
- Obfuscator 1.1.1
- Redactor 3.0.3
- SEOmatic 4.0.20
- Stripe for Craft Commerce 3.1.0
- Super Table 3.0.7
- Translations admin 3.0.1

**Comment by stefanfriedrich** [comment] 2023-02-24 16:59
correct purchasableId shows up in "_purchasableIds" from the sale.

**Comment by lukeholder** [comment] 2023-02-25 00:26
@stefanfriedrich can you confirm the product is marked as 'promotable' on the product edit page?

**Comment by stefanfriedrich** [comment] 2023-02-25 07:34
> @stefanfriedrich can you confirm the product is marked as 'promotable' on the product edit page?

@lukeholder Yes

**Comment by stefanfriedrich** [comment] 2023-02-25 08:51
<img width="374" alt="template" src="https://user-images.githubusercontent.com/1652761/221348147-e856fe6b-8cdb-48bc-b22a-1ecd01410898.png">
<img width="964" alt="sale" src="https://user-images.githubusercontent.com/1652761/221348154-73dca712-ac38-4fea-9ff7-aee8a81a6628.png">
<img width="967" alt="variant" src="https://user-images.githubusercontent.com/1652761/221348156-08d4577f-86fc-486c-9a93-ad5cb8cd798b.png">
<img width="942" alt="product" src="https://user-images.githubusercontent.com/1652761/221348157-fe087710-69a1-43a5-9389-887ee420e9ae.png">

**Comment by stefanfriedrich** [comment] 2023-02-27 13:23
@lukeholder 
problem seems to be here: src/services/Sales.php

// Category match
if (!$sale->allCategories) {
    $relatedTo = [$sale->categoryRelationshipType => $purchasable->getPromotionRelationSource()];
    $saleCategories = $sale->getCategoryIds();
    $relatedCategories = Category::find()->id($saleCategories)->relatedTo($relatedTo)->ids();

    if (empty($relatedCategories)) {
        return false;
    }
}

returns false also if no categories exist. quickfix right now is to set all categories active.

**Comment by pdaleramirez** [comment] 2023-02-28 06:41
![Screen Shot 2023-02-28 at 2 38 48 PM](https://user-images.githubusercontent.com/4172750/221774095-dfa05a05-8871-4b12-aa2e-775bceb950da.png)
The problem is that you are not selecting any categories in the matching items setting. You should turn on the `All categories` lightswitch input if you are not selecting a category.

Let us know if that works. @stefanfriedrich

**Comment by stefanfriedrich** [comment] 2023-02-28 07:21
@pdaleramirez 
=> returns false also if no categories exist. not sure if this should be the case. works as written before.

**Comment by pdaleramirez** [comment] 2023-03-02 05:56
@stefanfriedrich, if no categories exist, the value of the `$sale->allCategories` attribute returns to `true`, making all purchasable on sale. Turning on the `All categories` light switch should resolve the issue.

**Closed by pdaleramirez** 2023-03-02 05:56 UTC
Labels: 🧭 guide, commerce4

**Comment by stefanfriedrich** [comment] 2023-03-02 08:00
@pdaleramirez @lukeholder 
turning it on resolves the issue, but not the problem: if no categories exist it also should return true, not false.
