### ISSUE TITLE
Post Date is set to UTC when saving a new product with errors

### ISSUE THREAD

**Issue by martinleveille** [craftcms/commerce#795] opened 2019-03-19 14:36 UTC
### Description

When you create a new product without filling any fields and click the Save button, the page reload and shows you the errors. At this point, the Post Date field value is set with the UTC time zone.

This is problematic when you are in a negative time zone (like mine UTC-4) because if you are not careful about the Post Date field value, the product will be in pending status after a successful save.

If you try the same scenario with a regular Craft Entry, the Post Date field value is set using the time zone specified in your Craft General Settings.

### Steps to reproduce

1. Set your Craft time zone to UTC-4
2. Add a new product
3. Do not fill any fields and click the Save button
4. The Post Date field value is set to UTC

### Additional info

- Craft version: 3.1.18
- PHP version: 7.2.15
- Database driver & version: MySQL 5.7.25
- Plugins & versions: Commerce Pro 2.1.2

**Comment by lukeholder** [comment] 2019-03-28 12:52
Duplicate of #774 Which is now fixed for the next release.

**Closed by lukeholder** 2019-03-28 12:52 UTC
Labels: bug, working on it
