### ISSUE TITLE
Payment currency for orders is broken

### ISSUE THREAD

**Issue by jlachancekffein** [craftcms/commerce#1653] opened 2020-08-17 12:46 UTC
The currency information in the listing and in the detail of an order is incorrect.

Before the Craft Commerce update (3.1 -> 3.2), the currency related to the order was displayed correctly. Now the currency defined as primary is displayed.

In my example, the payment currency is CAD, but USD is displayed.

In attached file, the detail of the order and the dump of the order in sql.

![Capture d’écran 2020-08-17 à 08 35 56](https://user-images.githubusercontent.com/24896469/90397533-fd0c9380-e065-11ea-93f8-e044e9229ef2.png)
![Capture d’écran 2020-08-17 à 08 36 05](https://user-images.githubusercontent.com/24896469/90397543-00a01a80-e066-11ea-9640-a765026c59fb.png)

**Comment by nfourtythree** [comment] 2020-08-20 11:01
Hi @jlachancekffein 

This is a duplicate of #1406 

Will close this one and you will be able to follow along/add your feedback and thoughts on that issue.

Thanks!

**Closed by nfourtythree** 2020-08-20 11:01 UTC
