### ISSUE TITLE
Commerce no longer saving payment source

### ISSUE THREAD

**Issue by lukeyouell** [craftcms/commerce#694] opened 2019-02-07 15:53 UTC
### Description

Since updating to the latest version of commerce the `savePaymentSource` checkbox no longer saves the payment source when completing an order. 

I can see in the logs that this value is passed along to the controller, but the payment source isn't saved in the DB.

```
$_POST = [
    'CRAFT_CSRF_TOKEN' => '•••••••••••••••'
    'action' => 'commerce/payments/pay'
    'redirect' => '107a07bf8fdd04ba68b3a0a124a2fb28d1fb1716183ff5762de7a11b666e236aaccount/order?number=306b0276d64937eab59253273288898a'
    'cancelUrl' => '03928870d100ce989d623867faac22f193d3d2a06acbb2462b50a4cbd14f8414checkout/payment'
    'orderEmail' => 'luke@commerce.test'
    'gatewayId' => '3'
    'savePaymentSource' => '1'
    'stripeToken' => '••••••••••••••••••••••••••••'
]
```

![image](https://user-images.githubusercontent.com/24975058/52423699-8bf33400-2af0-11e9-9537-5e6288fbb64f.png)

I'm using the Stripe payment gateway.

### Additional info

- Craft version: 3.1.8
- Commerce version: 2.0.4

**Comment by lukeholder** [comment] 2019-02-18 05:51
Thanks for reporting, looking into this now.

**Comment by lukeyouell** [comment] 2019-02-18 09:06
Hi @lukeholder I managed to find the time to properly debug this and it turned out to be an issue related to the Stripe gateway plugin not being able to save payment sources if the customer record had been deleted from Stripe. Deleting the customer ID value from the database solved it. The main issue I ran into when debugging was that the whole process was failing silently!

**Comment by andris-sevcenko** [comment] 2019-02-18 10:53
Duplicate of craftcms/commerce-stripe#35

**Closed by andris-sevcenko** 2019-02-18 10:53 UTC
Labels: investigating
