### ISSUE TITLE
Make Shipping Method, Rule, Tax Category description translatable

### ISSUE THREAD

**Issue by chanwhab** [craftcms/commerce#457] opened 2018-08-23 16:06 UTC
### Description
Make Shipping Method, Rule, Tax Category name & description translatable.

Although the name & description is for CP usage,
but since they are also accessible in frontend using twig,
it would be nice to have them translatable in backend.

This will save a ton of works, and make updating shipping logic happy.

**Comment by lukeholder** [comment] 2019-10-10 23:46
Duplicate of #37

**Closed by lukeholder** 2019-10-10 23:46 UTC
Labels: 💡 enhancement, 💰 tax, 📬 shipping
