### ISSUE TITLE
Save as a new product loses relation and matrix field data

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1442] opened 2020-05-08 19:25 UTC
### Description

When using *Save as a new product* action existing data in relation and matrix fields is lost.

### Steps to reproduce

1. Open product edit page for product with relation and/or matrix fields with data.
2. Change SKU and any other necessary info, then click *Save as a new product*.
3. New product element is successfully created, but relation and matrix fields that were not empty are now empty after save.

### Additional info

- Craft version: Pro 3.4.18
- PHP version: 7.4.5
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce Pro 3.1.3

**Comment by lukeholder** [comment] 2020-05-10 04:07
Thanks, this is a known issue and will be fixed in the next release out early next week.

**Comment by lukeholder** [comment] 2020-05-14 05:36
Duplicate of #1393 will be fixed in the next release.

**Closed by lukeholder** 2020-05-14 05:36 UTC
Labels: 🐞 bug
