### ISSUE TITLE
Migrations MySQL Syntax Error in ALTER TABLE `xxx` CHANGE `xxx` `xxx`. (Missing datatype)

### ISSUE THREAD

**Issue by isjackwild** [craftcms/commerce#1210] opened 2020-01-09 15:51 UTC
### Description
I ran a recent batch of composer updates, and during the database migration (specifically Craft Commerce migration 'm191007_184911_orderStatus_from_archived_to_deleted'), the migration failed with a MySQL syntax error: 'Syntax error or access violation: 1064 You have an error in your SQL syntax;'

The SQL being executed was: ALTER TABLE `c_commerce_orderstatuses` CHANGE `dateArchived` `dateDeleted`

After some manual debugging and SQL validation, it appears that the error occurred because the datatype was left out of the query. (``"ALTER TABLE `c_commerce_orderstatuses` CHANGE `dateArchived` `dateDeleted` datetime" does pass validation``)

### Steps to reproduce

1. Run the Craft Commerce 'm191007_184911_orderStatus_from_archived_to_deleted' migration

### Additional info

- Craft version: Craft Pro 3.3.19
- PHP version: 7.2.24
- Database driver & version: MySQL 8.0.17
- Plugins & versions: Craft Commerce 2.2.13

**Comment by lukeholder** [comment] 2020-01-15 01:24
Unable to reproduce this. Could you send your full logs to support@craftcms.com

**Comment by lukeholder** [comment] 2020-01-15 01:26
Looks like I only tested on MySql 5.x - this seems like an issue with mysql 8?

**Comment by lukeholder** [comment] 2020-01-15 01:26
```
    public function safeUp()
    {
        $this->renameColumn('{{%commerce_orderstatuses}}', 'dateArchived', 'dateDeleted');
        $this->dropColumn('{{%commerce_orderstatuses}}', 'isArchived');
    }
```

**Comment by nfourtythree** [comment] 2020-01-15 08:47
Have just tested the migration on MySQL 8 and everything seemed to run correctly 🤔.

I am running version `8.0.17` as well.

**Comment by isjackwild** [comment] 2020-01-15 08:52
This is very odd. Perhaps there’s some form of safe mode my MySQL installation is running in. I’m using the Digital Ocean managed MySQL database.

I’ll try and find the logs today... I had to run an update on a separate local database migration and reupload it, so the logs might have been cleared from back then.

The thing that does seem off is that if you paste in the SQL which the migrator runs into an online SQL validator, it does say it’s not valid SQL as it’s missing the data type.

Thanks,
Jack.

**Comment by nfourtythree** [comment] 2020-01-15 09:19
That is strange. 

For MySQL we extend the mysql `QueryBuilder` which looks like where the `ALTER TABLE … CHANGE` query comes from: https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L101-L104

Interestingly enough the default SQL in the rename method in the top-level Yii2 `QueryBuilder` class works: https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L826-L831

Will have to look into this a little more.

**Comment by isjackwild** [comment] 2020-01-15 09:46
Thank you for looking into this further, I’m sure I can’t be the only one with the issue, I’m surprised it hasn’t come up.

If it’s helpful, I used this validator: https://www.piliapp.com/mysql-syntax-check/

👍 ALTER TABLE `mytable` CHANGE `oldname` `newname` int
👎 ALTER TABLE `mytable` CHANGE `oldname` `newname`

The error for the second one is: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Let me know if I can help with any more info, and I’ll try and find the logs.

Cheers,
Jack.


Jack Wild

Mobile: +447851 886 559
Skype: jk_dubya
Web: www.isjackwild.com<http://www.isjackwild.com>


On 15 Jan 2020, at 09:19, Nathaniel Hammond <notifications@github.com<mailto:notifications@github.com>> wrote:


That is strange.

For MySQL we extend the mysql QueryBuilder which looks like where the ALTER TABLE … CHANGE query comes from: https://github.com/yiisoft/yii2/blob/master/framework/db/mysql/QueryBuilder.php#L101-L104

Interestingly enough the default SQL in the rename method in the top-level Yii2 QueryBuilder class works: https://github.com/yiisoft/yii2/blob/master/framework/db/QueryBuilder.php#L826-L831

Will have to look into this a little more.

**Comment by mrunkel** [comment] 2020-03-17 15:08
Hey, just wanted to add a +1 I too am on Digital Ocean's managed MySQL offerring..  I've received this error in the Matrix Field Type when renaming a field, and I'm now experiencing it in SproutForms, so I think this problem is a little lower in the stack (maybe even a problem with the Yii2 QueryBuilder class.

**Comment by lukeholder** [comment] 2020-05-14 05:44
Going to close this, please leave a comment on https://github.com/craftcms/cms/issues/5804 if you have more information.

**Closed by lukeholder** 2020-05-14 05:44 UTC
Labels: 🔎 status: investigating
