### ISSUE TITLE
Improve Make Payment form for gateways using authorize only

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1369] opened 2020-04-08 14:13 UTC
### Description

Love the features you guys have added to give the ability to edit orders. However, it gets a bit tricky for us when editing orders because our gateway is set to authorize only and we do not capture until an order is shipped. This means that if someone calls in to edit an order, the only option available from the CP Make Payment form is to pay the updated full amount. Would it be possible to add the ability to change how much is charged? Or if you implemented the Omnipay `void()` method (which I see you've [had discussions about](https://github.com/craftcms/commerce/issues/611)), that would allow us to cancel the existing authorization and run a new charge for the full amount.

### Steps to reproduce

1. Check out an order using an authorize only gateway.
2. From CP edit order page, add a new line item and update the order.
3. Go to Transactions tab and click Make Payment. Form only allows to make a charge for the full order amount, rather than remaining balance.

### Additional info

- Craft version: 3.4.13
- PHP version: 7.2.24
- Database driver & version: MySQL 5.5.5
- Plugins & versions: Commerce 3.1.1

**Comment by lukeholder** [comment] 2020-04-09 06:51
Thanks for voicing this is important to you. We hope to have this done in the near future.

Closed as duplicate of https://github.com/craftcms/commerce/issues/611

**Closed by lukeholder** 2020-04-09 06:51 UTC
