### ISSUE TITLE
[4.x]: Coupon max uses incorrectly set to 0 instead of left blank after Commerce4 upgrade

### ISSUE THREAD

**Issue by samueldraper** [craftcms/commerce#2947] opened 2022-08-24 11:57 UTC
### Description

It would appear that Coupon codes created in Commerce3 are being set to max uses '0' after upgrading to Commerce4.

### Steps to reproduce

1. In control panel, go to Commerce > Promotions > Discounts
2. Choose a discount that has coupons. Select Coupons tab. 

### Expected behavior

Max uses should be set to blank in Craft 4 when upgrading from Craft 3

### Actual behavior

Coupons appear to be set to 0, when they should be blank.
i.e. the previous setting in Commerce 3 was ```Set to zero for unlimited use``` but the new setting is ```Leave blank for unlimited uses```

### Craft CMS version

Craft 4.2.2

### Craft Commerce version

Craft 4.1.0

### Installed plugins and versions

-

**Comment by nfourtythree** [comment] 2022-08-29 09:58
Hi @samueldraper 

Thank you for your message.

There was a bug in the initial migration, we have since pushed a fix for this and added a [note in the changelog](https://github.com/craftcms/commerce/blob/develop/CHANGELOG.md?plain=1#L43) for those that have upgraded early.

It would be advisable to check the values in your pre-upgraded DB against the current values.

Thanks.

**Closed by nfourtythree** 2022-08-29 09:58 UTC
Labels: 🐞 bug, commerce4

**Comment by bossanova808** [comment] 2023-05-22 04:34
I can confirm this is in fact not fixed and is still happening with a migration (C3C3 -> latest C4C4) - done just a couple of weeks ago - i.e. maxUses set to 0.

**Comment by nfourtythree** [comment] 2023-05-24 16:31
Hi @bossanova808 

Thank you very much for bringing this to our attention.

We have pushed a fix for the migration, meaning any future `3.x` to `4.x` migrations will not see this issue.

This fix will be included in the next release of Commerce 4.

Thanks!

**Comment by bossanova808** [comment] 2023-06-02 01:29
Jut confirming in my latest test migration this now went ok - many thanks!

**Comment by nfourtythree** [comment] 2023-06-02 05:59
Hi @bossanova808 

Thanks for confirming!
