### ISSUE TITLE
[RFC] Allow custom fields to be saved to the addresses

### ISSUE THREAD

**Issue by lenvanessen** [craftcms/commerce#815] opened 2019-04-05 09:12 UTC
It would be great if Craft allows custom fields to be saved to the addresses.
In our case, we need a separate field for the housenumber, as well as the addition, and some more. This is partly because we want to be sure that people don't forget to supply that info, because people sometimes forget, but partly because we integrate with a CRM that requires the fields to be separate.

Saving to the order in this case is not what we want, because we want this data to be persistent  between orders.

**Comment by sjcallender** [comment] 2019-04-05 10:52
Same as https://github.com/craftcms/commerce/issues/163

**Comment by lukeholder** [comment] 2019-07-03 09:29
Closed as Duplicate of #163

**Closed by lukeholder** 2019-07-03 09:29 UTC
