### ISSUE TITLE
Deleting a variant doesn't remove it from craft_commerce_variants table

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#734] opened 2019-02-20 08:17 UTC
### Description
When deleting a product variant it is removed from the CP but the row for the variant remains within the craft_commerce_variants table. This makes it impossible to create another variant using the same SKU.

### Steps to reproduce

1. Delete a product variant
2. Try to make a new variant with the same SKU

### Additional info

- Craft version: 3.1.12
- PHP version: 7.1.12
- Database driver & version: MySQL 5.6.38 (Also on 5.5.63)
- Plugins & versions: 
Craft Commerce	2.0.4
Colour Swatches	1.2.0
Contact Form	2.2.3
Contact Form Extensions	1.0.12
Feed Me	3.1.8
Feed Me Pro	3.0.4
Help	2.0.0
Imager	v2.1.4
Incognito Field	1.0.0
Kint	1.0.0
Many to Many Field Type	1.0.2.2
PayPal for Craft Commerce	1.0.0.1
Recently Viewed	1.0.2
Redactor	2.1.7
Relabel	1.2.2
Retour	3.1.2
Schematic	4.1.0
SEOmatic	3.1.38
Similar	1.0.5
Smart Map	3.2.1
Stamp	2.1.0
Stripe for Craft Commerce	1.0.10
Super Table	2.1.8
Typed link field	1.0.17
Units	1.0.3

**Comment by lukeholder** [comment] 2019-02-25 19:26
This is because the variant is soft deleted. Once garbage collection runs the SKU will become free.

Will need to fix this so the above is not necessary. Likely append a `-1` to the variant when initially trashing it.

**Comment by fantasticmachine** [comment] 2019-02-25 20:39
Ah I thought it might be to do with soft deletes. How can I force garbage collection to run?

**Comment by magnessjo** [comment] 2019-02-25 21:06
@fantasticmachine, you can run `./craft gc/run` in the root of the craft directory.  

Also `./craft help` for me.

**Comment by lukeholder** [comment] 2019-02-26 04:30
`./craft gc --delete-all-trashed`

**Comment by buesing** [comment] 2019-03-01 11:56
Hi @lukeholder, is a fix for this already in the making? This prevents us from automatically importing products (see also https://github.com/verbb/feed-me/issues/480), delaying the launch of the website we're working on. Would be great to have an update.

**Comment by lukeholder** [comment] 2019-03-02 11:12
Duplicate of #718

**Closed by lukeholder** 2019-03-02 11:12 UTC
Labels: bug

**Comment by lukeholder** [comment] 2019-03-02 11:14
Fixed for the next release in commit: 700bb31d13cbda444e214949f06f6fac9dacb0db
