### ISSUE TITLE
Error when displaying customers' addresses

### ISSUE THREAD

**Issue by Sam-Black-0013** [craftcms/commerce#755] opened 2019-02-27 09:13 UTC
### Description
I used this:
`{% set addresses = craft.commerce.customer.addresses %}`
to display customers addresses, but if i login as a user and add an address, then if i logout and login as another customer, this first customer's address that i added is displayed in the second one address book.
The cart does not get destroyed. Addresses get mixed up, craft does not return any errors to me. it says that the address was saved, but i have no idea to where or to whom. Are the addresses connected to a user or a session ?

### Additional info
- Craft version: 3.1.14
- Plugins & versions: Commerce 2.1.0.2

**Comment by lukeholder** [comment] 2019-03-05 17:53
Can you steps to reproduce using the example templates?

**Comment by Sam-Black-0013** [comment] 2019-03-12 18:54
I did and it is still the same. I guess it just a matter of sessions more than templates.

**Comment by lukeholder** [comment] 2019-08-28 09:41
Duplicate of #903

**Closed by lukeholder** 2019-08-28 09:41 UTC
Labels: status: need more info
