### ISSUE TITLE
Category Limit on Varaints visualy not limited

### ISSUE THREAD

**Issue by kaspar-allenbach** [craftcms/commerce#935] opened 2019-07-17 07:07 UTC
### Description

If I create a `category field` with the `limit: 1` and add this to a product variant in commerce it looks as if I could add more than one category: 

![Bildschirmfoto 2019-07-17 um 09 02 24](https://user-images.githubusercontent.com/762213/61354159-d207ad00-a871-11e9-8a22-7a250433faeb.png)

On the screenshots you can see two category field which ar both limited to 1 category but it appears as if I could add more than one (Which I can't. I can choose a second category but the second one is not added)

### Steps to reproduce

1. create a category field with the limit: 1
2. add the field to a variant in commerce 2

### Additional info

- Craft version: 3.2.2
- PHP version: 7.1.3
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Craft Commerce 2.1.7

**Comment by brandonkelly** [comment] 2019-07-19 10:46
This is a duplicate of craftcms/cms#2423.

**Closed by brandonkelly** 2019-07-19 10:46 UTC
Labels: status: investigating
