### ISSUE TITLE
Failed webhooks for Subscription with Payment Method Issue

### ISSUE THREAD

**Issue by fantasticmachine** [craftcms/commerce#2063] opened 2021-03-30 11:19 UTC
When a subscription has been moved into the "Payment Method Issue" section of the Subscriptions CP any Stripe webhooks for that subscription fail.

In our case, we have a couple of customers with subscriptions that failed payments. It looks like the payment method has then been updated. But when Stripe sends the webhook, it causes an error because the subscription cannot be found.
Stripe continues to send the webhook at decreasing time intervals.

The log says that the subscription cannot be found and refers to line 605 of commerce-stripe/src/bas/SubscriptionGateway.php

```
do {
            // Handle cases when Stripe sends us a webhook so soon that we haven't processed the subscription that triggered the webhook
            sleep(1);
            $subscription = Subscription::find()->reference($subscriptionReference)->one();
            $counter++;
        } while (!$subscription && $counter < $limit);


        if (!$subscription) {
            throw new SubscriptionException('Subscription with the reference “' . $subscriptionReference . '” not found when processing webhook ' . $data['id']);
        }
```

It would appear that the query that is meant to fetch the subscription fails. Is this perhaps because of a status?

**Expected behavior**
I'd expect the subscription to be reactivated and moved out of the Payment Method Issue section, and the webhook to succeed.

**Additional info**
- Craft version: 3.6.9
- Commerce version: 3.2.17

**Comment by fantasticmachine** [comment] 2021-03-30 11:35
I'll add, we are still investigating this as it might be something to do with the Stripe setting on how to handle a failed subscription.

**Comment by pdaleramirez** [comment] 2021-03-31 09:40
@fantasticmachine Let us know what you'll find. If the issue is on Stripe or Commerce side.

**Comment by fantasticmachine** [comment] 2021-03-31 17:11
Looks like there was something similar happening in https://github.com/craftcms/commerce-stripe/commit/d71dd172434a63b399d4bba89711738f8ad7baf5

**Comment by MattWilcox** [comment] 2021-04-10 14:31
I believe we have suffered the same issue recently.

A customer has signed up for a subscription, there's a record of the subscription on the Customer, but nothing shows up in the Commerce > Subscriptions area. Looking at the record on the customer, there was a billing issue recorded, AND their subscription is marked as paid. Looking in Stripe, the initial payment was declined due to insufficient funds, but then they have paid...

We have no way that I can see to mark that customers subscription as a valid subscription, and it looks like any automated method with webhooks is not working.

**Comment by pdaleramirez** [comment] 2021-04-15 08:24
I think this a similar issue here https://github.com/craftcms/commerce-stripe/issues/134. I am going to close this issue cause this is a Commerce stripe plugin issue.

**Closed by pdaleramirez** 2021-04-15 08:24 UTC
Labels: 📈 subscriptions, 🔎 status: investigating

**Comment by gazlawn22** [comment] 2021-04-15 08:49
I have the same issue, so far not on a large scale, but means that client is out of sync on a lot of their subscription orders.

**Comment by fantasticmachine** [comment] 2021-05-24 10:47
@pdaleramirez I don't think this is quite the same issue as the one you have referenced.

The issue is more akin to  craftcms/commerce-stripe@d71dd17 which @andris-sevcenko fixed. But his fix was in a different part of the codebase for a different circumstance.

In our case the customer's subscription renewal payment fails with Stripe. Commerce responds to this marking the subscription as suspended.

What this then means, is that if the subscription later receives a successful payment (for instance if funds become available on the card) the success webhook is sent to Commerce. But Commerce cannot retrieve the subscription because it is not looking for suspended subscriptions in its query.

This is becoming a serious issue for us as the customer base grows and our subscriptions become more popular. Any failed payments result in a suspended subscription that cannot be restarted by a subsequent successful payment.

Can someone take a closer look at this to confirm what I (and others here) think is happening?
