### ISSUE TITLE
Empty lineitem descriptions in create new order (Commerce 3.1.4)

### ISSUE THREAD

**Issue by bossanova808** [craftcms/commerce#1457] opened 2020-05-21 03:03 UTC
**Description**

After successfully updating to Commerce 3.1.4 (testing, on dev, no migration errors) - when I go to create a New order, there are no descriptions for the items to choose from:

![image](https://user-images.githubusercontent.com/731309/82518693-403c9080-9b63-11ea-8110-f32a97d39eba.png)

Searching using product and variant titles returns empty results, as well.

I've sent recent DBs, both pre and post migration to support@ in case you need those.

Thankyou!!

**To Reproduce**

    As above.
    Try to add a new line item to an order - see empty descriptions
    Try to search using a product name

**Versions**

![image](https://user-images.githubusercontent.com/731309/82518725-53e7f700-9b63-11ea-86e1-3f7494bce7b2.png)

**Comment by nfourtythree** [comment] 2020-05-21 06:12
Hi @bossanova808 

This seems like a duplicate of #1437 and #1307 

Could you please check your "Order Description Format" on your Product type and then resave your products in the command line with `./craft resave/products`.

Thanks.

**Closed by nfourtythree** 2020-05-21 06:12 UTC
Labels: New

**Comment by bossanova808** [comment] 2020-05-21 06:16
I use this, or similar in ~6 product types:

`{% if object.product.type.hasVariants %}{{ object.product.title }} - {{ object.title}}{% else %}{{ object.title}}{% endif %}`

...per, very long ago, Luke's advice.  That has/is working well for all things until now.  

I have already reverted to 2 on dev, so will have to try this later, but is there anything wrong with that, or should that work?

**Comment by nfourtythree** [comment] 2020-05-21 06:25
Hi @bossanova808 

Thank looks all good to me. I think the issue is that potentially the descriptions have not been generated. Running `./craft resave/products` should make sure that the descriptions are correct in the database (they live in the `commerce_purchasables` table).

Thanks.
