### ISSUE TITLE
Tax categories are being ignored, applied to wrong category items

### ISSUE THREAD

**Issue by echantigny** [craftcms/commerce#842] opened 2019-05-02 12:54 UTC
### Description
I have 2 tax categories.  One category with rates applied on Order total taxable, the other category with only one rate (not even sure I need to have the rate) to make it to 0%/no taxes.

When I choose the No Tax category on my product and add it to the cart, both tax rates are being applied.

Expected behaviour:  Order total taxable rates would only apply to Line Items that are part of that category.

Side note:
I also tried to toggle the `Is this tax is already included in the taxable subject?`, but I got the message `Included tax rates are only allowed for the default tax zone.`.   I thought that if I checked that, maybe those "no taxes" products would be ignored by other taxes.

### Steps to reproduce
I'm adding screenshot at the end here with all the steps I have, but here the run down

1. Create a tax category (GST) with one rate of 5% applied to Order total
2. Create a tax category (no taxes) with one rate of 0% applied to Line Item (can we have a category with no rates at all? Tried it with same result anyway)
3. Create a product and choose the "No taxes" category
4. Add that product to your cart to see that both taxe rates are being applied to it's price.

### Additional info

- Craft version: Craft Pro 3.1.25
- Craft Commerce : 2.1.4
- PHP version: 7.2.4
- Database driver & version: MySQL 5.7.21

![2019-05-02 08_30_10-Tax Categories - Tax - Great Boardgames](https://user-images.githubusercontent.com/4933333/57076517-db906880-6cb7-11e9-821a-d976d413160b.png)
![2019-05-02 08_30_27-No taxes - Great Boardgames](https://user-images.githubusercontent.com/4933333/57076518-db906880-6cb7-11e9-9f8f-64df2e4466f1.png)
![2019-05-02 08_30_48-GST - Great Boardgames](https://user-images.githubusercontent.com/4933333/57076519-db906880-6cb7-11e9-8238-53516af2a6d0.png)
![2019-05-02 08_33_56-Test Product (no taxes) - Great Boardgames](https://user-images.githubusercontent.com/4933333/57076520-db906880-6cb7-11e9-816d-e75974ffa302.png)
![2019-05-02 08_34_30-Shopping Cart – Great Boardgames](https://user-images.githubusercontent.com/4933333/57076521-db906880-6cb7-11e9-848b-896984af0019.png)

**Comment by lukeholder** [comment] 2019-05-08 03:46
Duplicate of https://github.com/craftcms/commerce/issues/538

**Closed by lukeholder** 2019-05-08 03:46 UTC
Labels: status: investigating, 💰 tax

**Comment by pixelmachine** [comment] 2019-09-11 05:12
@lukeholder I don't believe this is fixed and it's not the same as #538 

I have a very similar setup to the one @echantigny described with two tax rates and two categories applying to different products (VAT and no tax).

Commerce is not honouring the "Available to Product Types" setting – applying the wrong tax rates to products in a different tax category. 

Setting the "Taxable Subject" for both tax rates to line items, sets one of the tax rates on all items even where the products are in a different category.
Setting the "Taxable Subject" for both tax rates to the order total, results in both tax rates being shown incorrectly.

This is when amending the tax rules on existing products.

**Comment by nfourtythree** [comment] 2019-09-23 08:32
HI @pixelmachine 

Just been having a look at this and I don't believe I can replicate the issue you explained on the latest version of Commerce.

For example in the screenshot below I have two tax categories `General` and `No tax` they each have a rate assigned. `General` has `VAT` which is 20% on the line item and `General` is set be the default if no other categories are available to the product type. `No Tax` has a `Zero rate` applied to the line item and it is set to only be available on the `Kids - Clothing` product type.

Here is the Cart, showing what I would expect where the first item is in the `Clothing` product type and the second item is in the `Kids - Clothing` product type.

![](http://x.n43.me/791333185c95/Screenshot%202019-09-23%20at%2009.27.35.png)

It might be worth testing your setup on a fresh install of Commerce locally and using the example templates to see if everything works as expected.
