### ISSUE TITLE
Versioning of commerce Products?

### ISSUE THREAD

**Issue by kaspar-allenbach** [craftcms/commerce#1276] opened 2020-02-11 08:08 UTC
### Description

How about products have the same versioning feature as regular craft entries, no?

Versioning for the win ✨🥳
![Bildschirmfoto 2020-02-11 um 09 06 29](https://user-images.githubusercontent.com/762213/74219686-cf592300-4cad-11ea-9e6f-77bcd787d0fa.png)

No versioning on commerce products 🥺😢

![Bildschirmfoto 2020-02-11 um 09 07 07](https://user-images.githubusercontent.com/762213/74219734-f0217880-4cad-11ea-93bc-5f35b7b96b70.png)

**Comment by lukeholder** [comment] 2020-02-13 21:14
Duplicate of https://github.com/sidkshatriya/dontbug

**Closed by lukeholder** 2020-02-13 21:14 UTC
Labels: 👚 products, 💡 enhancement
