### ISSUE TITLE
Override default event (send email) on order status change

### ISSUE THREAD

**Issue by sjcallender** [craftcms/commerce#471] opened 2018-08-29 15:00 UTC
After changing an order's status in the CP, allow a way to manually prevent the notification email (if active) from sending. Sometimes we don’t want those emails to go out because of a back-end status change error. I can flesh this idea out more if it’s interesting. But initially, an MVP would be to ask if the email should be generated or not.

**Comment by lukeholder** [comment] 2019-10-10 23:59
Commerce 3 will let you send an email only without changing the status.

Close this due to duplicate of https://github.com/craftcms/commerce/issues/49

**Closed by lukeholder** 2019-10-10 23:59 UTC
Labels: 💡 enhancement
