### ISSUE TITLE
[4.6]: Disabled variant is unable to be re-enabled.

### ISSUE THREAD

**Issue by aaronrobb** [craftcms/commerce#3555] opened 2024-06-24 14:35 UTC
### Description
After disabling a variant in the CMS admin, it gets greyed out and not clickable. But when we want to re-enable it, there is no way to do it since its fully unclickable. 

### Steps to reproduce

1. Create variants under a product
2. Disable one variant via the gear icon on that variant
3. Variant block becomes disabled, greyed out and not clickable.

### Expected behavior
A disabled variant should be able to be re-enabled when needed.

### Actual behavior
Unclickable, greyed out variant block.

<img width="810" alt="Screenshot 2024-06-24 at 10 30 26 AM" src="https://github.com/craftcms/commerce/assets/677551/631c00a5-5b70-4490-99e9-fd8fc602418a">

### Craft CMS version

Craft Pro 4.9.4

### Craft Commerce version

4.6

### PHP version

8.3.7

### Installed plugins and versions

-

**Comment by lukeholder** [comment] 2024-06-25 05:06
Hi, thanks for reporting. Can you confirm this is happening the lastest 4.x versions of Craft and Commerce? I just tried it and couldn't reproduce on the latest 4.x

**Comment by philipboomy** [comment] 2024-06-26 05:56
I am on 4.6.2 and my disabled variants are not greyed out and I have the red dot. I can enable without issues.

**Comment by aaronrobb** [comment] 2024-06-26 16:35
I can confirm that updating to 4.6.2 is where the variant works again.

**Comment by lukeholder** [comment] 2024-06-28 06:36
This should be fixed by updating to the latest 4.x release. Thanks.

**Closed as completed by lukeholder** 2024-06-28 06:36 UTC
Labels: bug, commerce4, Craft Commerce
