### ISSUE TITLE
Cannot delete initial Products or Product Type

### ISSUE THREAD

**Issue by carolineboeykens** [craftcms/commerce#677] opened 2019-02-01 09:37 UTC
### Description
We tried deleting the initial Craft Commerce Products and Product Type (Clothing) but get the error: Invalid product ID: 1161.

If we try deleting the product from the product page we get this error:

```
yii\base\InvalidConfigException: Invalid product ID: 1161 in /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/commerce/src/elements/Variant.php:302
Stack trace:
#0 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/commerce/src/elements/Variant.php(282): craft\commerce\elements\Variant->getProduct()
#1 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/base/Element.php(2072): craft\commerce\elements\Variant->getFieldLayout()
#2 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/base/Element.php(1893): craft\base\Element->fieldLayoutFields()
#3 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/services/Elements.php(957): craft\base\Element->beforeDelete()
#4 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/services/Elements.php(937): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Variant))
#5 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/commerce/src/elements/Product.php(766): craft\services\Elements->deleteElementById(1162, 'craft\\commerce\\...')
#6 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/services/Elements.php(1002): craft\commerce\elements\Product->afterDelete()
#7 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/commerce/src/controllers/ProductsController.php(175): craft\services\Elements->deleteElement(Object(craft\commerce\elements\Product))
#8 [internal function]: craft\commerce\controllers\ProductsController->actionDeleteProduct()
#9 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('delete-product', Array)
#12 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('delete-product', Array)
#13 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('commerce/produc...', Array)
#14 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('commerce/produc...', Array)
#15 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#16 /Users/carolineboeykens/Documents/Sites/kbvpla/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#17 /Users/carolineboeykens/Documents/Sites/kbvpla/public/index.php(21): yii\base\Application->run()
#18 {main}
```
If we try to delete the product from the overview we only get the flash message from Craft: An error occurred.

### Steps to reproduce

1. Go to Commerce > Products
2. Delete a product from the Clothing product type

### Additional info

- Craft version: 3.1.6.1
- PHP version: 7.2.10
- Database driver & version: 5.7
- Plugins & versions: Craft Commerce Lite 2.0.2

The website is a mulitsite.
We think it could be related to this issue #405 but if we disable the products the error still appears.

**Comment by lukeholder** [comment] 2019-02-01 16:58
Duplicate of #650 which is fixed for the next release.

**Closed by lukeholder** 2019-02-01 16:58 UTC
