### ISSUE TITLE
Order History Records Deleted

### ISSUE THREAD

**Issue by jmauzyk** [craftcms/commerce#1172] opened 2019-12-10 14:40 UTC
### Description

Running into an issue where orders are having all but their first order history deleted, seemingly at random.

### Steps to reproduce

This has been difficult to reproduce. There are not any error messages being thrown that I can see. It seemed like it might be happening when queue jobs are run, and from some basic logging I've been doing it looks like it might be happening when `UpdateSearchIndex` jobs are run. However, it does not happen with any consistency and the orders affected do not necessarily correspond to the order in the `UpdateSearchIndex` job. This issue may have coincided with the update to Craft 3.3.15. We are using the AsyncQueue plugin, not sure if that could be playing a role as well.

### Additional info

- Craft version: Pro 3.3.17
- PHP version: 7.2.24
- Database driver & version: MySQL 5.7.28
- Plugins & versions:
  - AsyncQueue: 2.0.0
  - Avatax: 2.0.7
  - CardConnect for Craft Commerce: 1.0.1
  - Craft Commerce: Pro 2.2.8
  - Freeform: Pro 3.5.6
  - PayPal for Craft Commerce: 2.1.0.1
  - Queue Manager: 1.2.0
  - Redactor: 2.4.0
  - SEO: 3.6.2
  - Shipstation Connect: 1.2.7
  - Sprout Encode Email: 2.0.7
  - SuperSort: 3.0.1
  - Videos: 2.0.10
  - Wordsmith: 3.1.1

**Comment by lukeholder** [comment] 2019-12-30 19:59
Not sure how this could happen. Need steps to reproduce. Closing for now unless we get more information.

**Closed by lukeholder** 2019-12-30 19:59 UTC

**Comment by dhahn** [comment] 2020-07-23 19:56
We are also experiencing this issue but we have no idea why. Roughly 20% of our orders don't have any order histories status and it looks to be fairly consistent throughout the years. Will try to reproduce and figure it out but wanted to let you know we also noticed this.

**Comment by brandonkelly** [comment] 2020-09-18 19:35
@jmauzyk @dhahn Are you using DB read/write splitting on the projects affected by this bug?

**Comment by dhahn** [comment] 2020-09-18 19:51
No, but it's actually something we're looking at adding soon-ish

**Comment by brandonkelly** [comment] 2020-09-18 19:57
Alright, thanks. We just tracked down a different bug that ended up being caused by read/write splitting, and thought perhaps this one could be related.

**Comment by jmauzyk** [comment] 2022-03-01 14:57
@lukeholder a couple years later and completely by accident, I've managed to figure out what's going on here and how to replicate this. When a repeat guest customer starts a new order, a new customer record is created for their cart. At some point during placing and finalizing the order, the customer ID for the order is reassigned to their previous existing customer ID. However, the customer ID on the initial order status history is not changed. As a result, when garbage collection is run and the new customer record is deleted, the initial order status history is also deleted because the `comerce_orderhistories.customerId` foreign key is set to cascade on delete.
