### ISSUE TITLE
[5.x]: Order is duplicated after Mollie received the payment

### ISSUE THREAD

**Issue by MatthiasBrodelet** [craftcms/commerce#3705] opened 2024-10-03 09:05 UTC
### Description
A customer placed an order on 1 October and chose to pay with a Mollie SEPA bank transfer.
The customer paid today on the 3th of October.
For some reason a new order was created for this client without any line items.
All the user information and custom order fields are exactly the same as the original order. Except for the line items as mentioned.
It also does not have a transaction defined.
The paid status however is completed with the exact amount of the original order which did not get the updated payment status.
The new order was created at the exact same time when the payment came through.

I did change 1 thing in between the 2 orders: I changed the Order Reference Number Format for the store.
Previously it would be `{orderTimestampYmd}-{seqential number that gets reset every day}` and it was changed to `{orderTimestampYmd}-{seqential number that gets reset every year}`.

Could it be that this created a bug where the previously created Mollie webhook now lost its link with the original order?

I can send some screenshots or even the database via mail if needed.

Edit: I was wrong about the total amount being the same in both orders. The original order was € 15.824,50 and the second was 
€ 15.784,00. Mollie did send a payment request for the original amount so I am going to have a look in the Mollie dashboard to see what happend there. Still weird to see that an order was automatically created without a transaction or line items though.

2nd edit: I went looking in the database and saw that the second order was created 45 minutes after the first one was concluded and ordered. Keep in mind that this is an order without line items. A day later a transaction was created with status `redirect` and the day after another transaction with status `success`. So the `processing` transaction is missing in the 2nd order.

At first I thought that the customer clicked the browser back button on the order completed screen to start another Mollie transaction but in that case the order ID stays the same so that can't be it.
When the customer clicks the back button twice to go back to the last checkout page they are redirect to an empty shopping cart.

How could this be possible?

### Steps to reproduce

1. I don't know yet.

### Expected behavior
The order should not be created again when the payment is received.

### Craft CMS version

5.x

### Craft Commerce version

5.x

### PHP version

8.2

### Installed plugins and versions

-

**Comment by nfourtythree** [comment] 2024-10-04 07:42
Hi @MatthiasBrodelet 

Thank you for providing such a detailed report. I understand how frustrating and unusual this situation must be.

A couple of key points stand out from your description. You mentioned that the second order was created 45 minutes after the first one, which suggests there may have been some user interaction involved. Given that Mollie’s returned transaction data wouldn't automatically trigger the creation of a new order, it seems we might be able to rule out the payment system as the direct cause.

The timings you've mentioned for the second order don't seem unreasonable on their own—for instance, a customer could create a cart one day, return the next, proceed with payment using an asynchronous payment method, and the transaction is completed via a webhook call. However, the missing line items are definitely concerning and unusual.

Regarding the "clicking back twice" scenario you mentioned, if this occurs after the order has been completed, the empty cart behaviour is expected since a new cart would be initiated at that point.

At this stage, I would also be curious to know if you've noticed any other orders exhibiting similar behaviour or any patterns that might provide further insight into what could be happening The more information we can gather, the easier it will be to pinpoint the cause.

Thanks again for your thoroughness in reporting this, hopefully, we can get to the bottom as to what might have happened in this instance.

Thanks!

**Comment by MatthiasBrodelet** [comment] 2024-10-04 09:28
@nfourtythree Currently I have not seen this happen with another customer or order.
I am also pretty sure this issue is the result of a specific user action since other users did not have this issue.

I can also rule out my first guess where this issue would occur because a user made an order before I changed the order Reference Number Format. Other orders made before the change have now paid with a Mollie bank transfer without issue.

Both orders are linked to the same customer.
This customer has created their account using the register page (I keep track of how new users are created in a custom user field).

Since there have been 2 redirect transfers I am pretty sure the user has seen 2 different payment screens.
On the first payment screen they have entered their email address, on the second they did not. I can verify this in the Mollie dashboard since both transactions are visible there.

This brings me to the following timeline:
1. Order 1 is created at `2024-10-01 13:35:36` with ID 194053
2. Transaction 1 for order 1 is created at `2024-10-01 14:20:27` with status redirect
3. Order 2 is created at `2024-10-01 14:21:15` with ID 194695
4. Transaction 2 for order 1 is created at `2024-10-01 14:25:00` with status processing => user entered their email address on the mollie payment screen
5. Transaction 1 for order 2 is created at `2024-10-02 06:11:25` with status redirect 
6. Transaction 2 for order 2 is created at `2024-10-03 07:27:44` with status success

Since there is no processing transaction for the 2nd redirect transaction I can only assume the client did not enter their email address and paid directly with the info visible on the screen.

The big question of course is how the 2 orders got mixed up.
The difference in price is explainable by the variable prices which get updated every minute.
So if the second order was created some time later then it is perfectly possible the price would be a little bit less than the first order.

The client has said to only want to make 1 order (the original one).
As far as we know there was no bad intention on their part.

**Comment by nfourtythree** [comment] 2024-10-07 12:57
Hi @MatthiasBrodelet 

Thank you for the information and feedback. As you stated it does appear that this all ties in around specific user interaction. From the timeline you stated it appears that the likely scenario is that they tried to do a second order. Maybe they weren't convinced the first went through correctly?

Unfortunately, this seems like one of those unknown situations. With you not being able to reproduce it or, indeed, seeing any other issues with the same outcome it is probably wise to close this issue for now and then reopen it if more concrete information becomes apparent.

Please let us know if there is any further update on this and we can work together to try and resolve whatever is may be.

Thanks!

**Closed as completed by nfourtythree** 2024-10-07 12:57 UTC
Labels: ℹ️ status: need more info, commerce5, Craft Commerce
